### ISSUE TITLE
BlockParser  logics

### ISSUE THREAD

**Issue by mironovalexey** [yuin/goldmark#1]
Thank you for the excellent markdown processor. This is really very impressive.

Could you please help me to understand the logic of BlockParser. 

For example, I want to implement the behaviour of (nesting) lists/blockquotes with help of markers, i.e

```
%START%

Content 1

%START%

Content2

%FINISH%

Content 3

%FINISH%
```

should produce 

```
<START>
Content 1
<START>
Content 2
</FINISH>
Content 3
</FINISH>
```

But when I write something like [this](https://github.com/mironovalexey/gm-test/blob/master/note/run.go), I am a little bit confused. It interrupts the parsing along with the first [parser.Close](https://github.com/mironovalexey/gm-test/blob/master/note/run.go#L78) call. But blockquote works well and there could be multiple parser.Close calls during the nested blockquotes parsing cycle.

**Comment by yuin** [comment]
Thank you for trying goldmark out!

It seems that you try to define a nestable structure without any indents.
Generally, Nestable markdown elements are designed that can be parse by indentations.
That's because Markdown was designed that can be easy-to-read, easy-to-write plain text format.
(Nestable markup without indentations are hard to realize that it is a nested in plain text format.)

If you want to define a nestable structure without any indentations, you should control nesting structures by a stack on `ParseContext`.

pseudo code:

```
var key = NewContextKey()

open() {
   if %START% in currentline {
     node = new node;
     pc.Set(key, append(pc.Get(key), node))
     reader.Advance(n)
     return node, HasChildren 
   }
}

close(node) {
  if %FINISH% in currentline && node == pc.Get(key).last {
    reader.Advance(n)
    return Close
  }
  return Continue | HasChildren
}

```

**Comment by mironovalexey** [comment]
Aha, thanks a lot, I'll give it a try.

> Generally, nestable markdown elements are designed that can be parsed by indentations.
> That's because Markdown was designed that can be easy-to-read, easy-to-write plain text format.

Yes, I know John Gruber's principles. But many things are hard  to express in such way. Or hard to maintain.

Example:

```markdown
> **Note**
>
> This is:
>  1. Inconvenient.
>  1. Fragile.
```

**Comment by yuin** [comment]
Markdown block elements are categorized into two types: [Container blocks] and [Leaf blocks].

"Nestable" means it is a container block. Your 2nd example seems leaf blocks. Notes in notes are barely needed.

Fenced code block is similar to your first example( `%START%`, `%END%` ), but it is designed as
leaf blocks.

Anyways, it can be implemented with a stack on `ParseContext` . I hope you will go well.

[Container blocks]: https://spec.commonmark.org/0.29/#container-blocks
[Leaf blocks]: https://spec.commonmark.org/0.29/#leaf-blocks

**Comment by yuin** [comment]
I close the issue due to inactivity. Please feel free to reopen the issue if you have any concerns.
