### ISSUE TITLE
Incorrectly escapes HTML in output

### ISSUE THREAD

**Issue by frioux** [yuin/goldmark#100]
- [x] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).
- [x] **goldmark is not dedicated for Hugo**. If you are Hugo user and your issue was raised by your experience in Hugo, **you should consider create issue at Hugo repository at first** .
- [x] Before you make a feature request, **you should consider implement the new feature as an extension by yourself** . To keep goldmark itself simple, most new features should be implemented as an extension.

1. What version of goldmark are you using? : v1.1.22
2. What version of Go are you using? : 1.13.4
3. What operating system and processor architecture are you using? : Linux, x86_64
4. What did you do? : Tried to render a link with html in it (` * <img ...>`)
5. What did you expect to see? : an image
6. What did you see instead? : raw html
7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?: yes

Here's a full repro:

```golang
package main

import (
        "fmt"
        "os"

        "github.com/yuin/goldmark"
        "github.com/yuin/goldmark/parser"
        "github.com/yuin/goldmark/renderer/html"
)

func main() {
        gold := goldmark.New(
                goldmark.WithParserOptions(
                        parser.WithAutoHeadingID(),
                ),
                goldmark.WithRendererOptions(
                        html.WithUnsafe(),
                ),
        )

        if err := gold.Convert([]byte(` * <img href="doesntmatter.jpg />"`), os.Stdout); err != nil {
                fmt.Println(err)
                os.Exit(1)
        }
}
```

If you can point out where to look I am interested in trying to help fix this.

**Comment by yuin** [comment]
You might have just making a typo.

```
 * <img href="doesntmatter.jpg />"
```
to
```
 * <img href="doesntmatter.jpg" />
```

works for me.

**Comment by frioux** [comment]
Thank you; that's embarrassing, but I guess the best outcome anyway! ;)
