### ISSUE TITLE
Improve label matching (unicode case fold)

### ISSUE THREAD

**Issue by jsteuer** [yuin/goldmark#103]
1. What version of goldmark are you using? : `v1.1.22`
2. What version of Go are you using? :  `1.13.7`
3. What operating system and processor architecture are you using? : `linux/amd64`
4. What did you do? :

    I was playing around with the newest version of the spec and found a bug on processing the following:

        [daß] is the old german spelling of [dass]

        [daß]: www.das-dass.de

5. What did you expect to see? :

        <p><a href="www.das-dass.de">daß</a> is the old german spelling of <a href="www.das-dass.de">dass</a></p>
 
6. What did you see instead? :

        <p><a href="www.das-dass.de">daß</a> is the old german spelling of [dass]</p>

7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?:

    Yes: [CommonMark online demo Example](https://spec.commonmark.org/dingus/?text=%5Bda%C3%9F%5D%20is%20the%20old%20german%20spelling%20of%20%5Bdass%5D%0A%0A%5Bda%C3%9F%5D%3A%20www.das-dass.de)

    
---

> One label matches another just in case their normalized forms are equal. To normalize a label, strip off the opening and closing brackets, **perform the Unicode case fold**, strip leading and trailing whitespace and collapse consecutive internal whitespace to a single space. 
>
> -- [Specification](https://spec.commonmark.org/0.29/#matches)

I think the function `ToLinkReference` in `util/util.go` is the problem, since it does not perform the  _Unicode case fold_. If using a [Caser](https://godoc.org/golang.org/x/text/cases#Fold) with a dependency to `golang.org/x/text` is OK for you, I can create a pull request.

**Comment by yuin** [comment]
> If using a Caser with a dependency to golang.org/x/text is OK for you, I can create a pull request.

No it isn't. goldmark is boasting "Depends only on standard libraries." in [README](https://github.com/yuin/goldmark#features).
