### ISSUE TITLE
On attributes once again

### ISSUE THREAD

**Issue by tommiv** [yuin/goldmark#109]
1. What version of goldmark are you using? : 1.1.4
2. What version of Go are you using? : go1.13.7 darwin/amd64
3. What operating system and processor architecture are you using? : macOS, x64
4. What did you do? : I want to implement custom attributes support on <a> tags
5. What did you expect to see? :
6. What did you see instead? :
7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?: NO
8. (Feature request only): Why you can not implement it as an extension?: 

So, our SEO team pushes me to support some attributes on anchor tags, for example `rel="noopener"`. According to commonmark specs the only attribute supported is `title`. So this feature should obviously be an extension. However, I took a glance on the project source and specifically this PR https://github.com/yuin/goldmark/pull/72/commits/5690da2615cbaaa7cefe47222f90dba5dc4f0b08 and came up with a conclusion that I will need to explicitly repeat all the parsing and rendering code with only slight modifications. I'm not sure if this is the right way to achieve what I need. Additionaly, this way will become even more cumbersome in case we need some more attributes on other elements (class/srcset on img, blockquote "types" via class, `data-*` attributes to enable some scripting on elements like rich embeds, you name it). Finally, the question itself: am I get it right that to support a custom attribute on a random element I need to explicitly copypaste a whole bunch of an existing project code and create an extension based on it with minimal modifications? If so, I'll probably stick to raw HTML blocks to achieve my goal for now.

P.S. I see the `parser.WithAttribute` extension in docs, but it support headers only. Would it be too hard or "just wrong" to enable it for other elements as well and/or make it configurable?

**Comment by yuin** [comment]
First, An HTML is just an output format that is supported by goldmark. For example, [glow](https://github.com/charmbracelet/glow) renders markdown into a terminal using goldmark.

goldmark is designed as flexible and does not stick with HTML.

So we must be able to known certain attribute should be rendered as an **HTML** attribute or not. Builtin html renderers uses pre-defined white list for this purpose. Builtin renderers renders attributes that are included in white list and renders attributes that **has `data-` prefix** .  Thus builtin renderers can render all **valid**  HTML attributes.

> Finally, the question itself: am I get it right that to support a custom attribute on a random element I need to explicitly copypaste a whole bunch of an existing project code and create an extension based on it with minimal modifications? If so, I'll probably stick to raw HTML blocks to achieve my goal for now.

So you do not need to copypaste to support custom attributes with builtin renderers. You can write [this](https://github.com/mdigger/goldmark-attributes) kind of extension or `ASTTransformer` that adds attributes for the elements.

**Comment by tommiv** [comment]
Thank you for an extended answer! At first sight the mdigger's extension is what I'm looking for excepting it's for block elements. But I assume inline elements support is a low-hanging fruit, I'll try to modify it for my needs. Great job on this library btw.
