### ISSUE TITLE
Question: guide to creating an extension to parse/render custom markdown

### ISSUE THREAD

**Issue by copernico** [yuin/goldmark#114]
Hi, I would like to write my own extension to parse and render code such as:
 ```
::: {#id class-a class-b}
Blah blah blah (and other markdown)
:::
```
as, for example:
```
<div id="id" class="class-a class-b>
Blah blah blah (and other markdown)
</div>
```
Could you point me to some documentation about how to write an extension like this?

If that does not exist, I am ok reading source code, but I would appreciate if you could provide some guidance as to which existing extension I could study and take as a starting point.
Thanks for your help, keep up the good work!

EDIT: **elaborating a bit:** I took a look at https://github.com/litao91/goldmark-mathjax/ and that would be the starting point I was looking for except, in my case, I would need to parse also the markdown content between the two `:::` marker lines (in other words, the node corresponding to the custom block I'm trying to define is not a leaf in the AST). How can I achieve that?

**Comment by yuin** [comment]
>  in my case, I would need to parse also the markdown content between the two ::: marker lines

```
return parser.Continue | parser.NoChildren
```

to

```
return parser.Continue | parser.HasChildren
```

and [goldmark-highlighting](https://github.com/yuin/goldmark-highlighting) would be helpful for parsing attributes like `{#id class-a class-b}` .

**Comment by copernico** [comment]
Thanks @yuin , I'll take a closer look at [goldmark-highlighting](https://github.com/yuin/goldmark-highlighting)!
