### ISSUE TITLE
sometimes 100% CPU spin during init phase in Go 1.14

### ISSUE THREAD

**Issue by yuin** [yuin/goldmark#116]
Go 1.14 has a [critical bug github.com/golang/go/issues/37741](https://github.com/golang/go/issues/37741) and it sometimes  causes 100% CPU spin during init phase.

So I would recommend Go 1.13 to goldmark users until this bug is fixed.

/cc @bep

**Comment by mholt** [comment]
Looks like a patch was merged into Go, and it should be released with Go 1.14.1.

**Comment by bep** [comment]
As to Hugo, I have not experienced this 1 time and had zero reports about it, so I think I'll just wait silently for the patch.

**Comment by yuin** [comment]
[Patch](https://github.com/golang/go/issues?q=milestone%3AGo1.14.1+label%3ACherryPickApproved) got merged into 1.14.1.
