### ISSUE TITLE
Possible regression of attributes after v1.1.30 fix

### ISSUE THREAD

**Issue by zzwx** [yuin/goldmark#124]
I know that the attributes implementation is prone to changes, I just want to confirm that this was an intentional fix.

Both of these pattern:
```
## Test {#hey .sort,class=fine,class=shell} Doesn't matter
## Test ## {#hey .sort,class=fine,class=shell} Doesn't matter
```
used to render as:

```html
<h2 id="hey" class="sort fine shell">Test</h2>
<h2 id="hey" class="sort fine shell">Test</h2>
```
(omitting the **`Doesn't matter`** part completely and ignoring trailing **`##`** of the title)

Since the latest fix, **v1.1.30** (I couldn't confirm `v.1.1.29` due to SECURITY ERROR) now renders it as:

```html
<h2 id="test-hey-sortclassfineclassshell-doesnt-matter">Test {#hey .sort,class=fine,class=shell} Doesn't matter</h2>
<h2 id="hey" class="sort fine shell">Test</h2>
```

Here's the test to confirm (which didn't fail in **v1.1.28**):

```go
func ExampleAttr_Heading_Without_EndingHash() {
	var source = []byte(`## Test {#hey .sort,class=fine,class=shell} Doesn't matter`)
	var md = goldmark.New(goldmark.WithParserOptions(
		parser.WithAutoHeadingID(),
		parser.WithAttribute(),
	),
	)
	var buf bytes.Buffer
	if err := md.Convert(source, &buf); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s", buf.String())

	buf.Reset()
	source = []byte(`## Test ## {#hey .sort,class=fine,class=shell} Doesn't matter`)
	if err := md.Convert(source, &buf); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s", buf.String())
	// Output: <h2 id="hey" class="sort fine shell">Test</h2>
	// <h2 id="hey" class="sort fine shell">Test</h2>
}
```

**Comment by yuin** [comment]
Thanks @zzwx for pointing out this. This is an intentional fix. I've add test cases for this issue.

**Comment by zzwx** [comment]
@yuin, are you saying that both cases shouldn't recognize the parameters? My tests were to show that the first one would fail, but the second continued to render parameters fine.

**Comment by yuin** [comment]
@zzwx 

> are you saying that both cases shouldn't recognize the parameters?
Yes. Attributes for headings must be at end of the line.
