### ISSUE TITLE
Option to leave HTML blocks alone

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#125]
I have been asked by the Kubernetes project to assist them getting their documentation site up and running with Goldmark (and the latest Hugo).

This site has lots of HTML blocks mixed in the Markdown files. Blackfriday left some block level HTML elements as-is (most notably `div`), while GoldMark parses the inner block as (potentially) Markdown -- adding paragraphs and doing its autolinking on already linked links etc.

I guess there are people who may want the current behaviour, but for the Kubernetes site (thousands of documents) this is very hard to tackle without massive amounts of manual editing.

I don't understand the "how difficult this would be", but I suspect that more people would appreciate such an option.

```md
This is some **HTML** in a DIV block:

<div class="community_main">
<h1>Kubernetes Community Code of Conduct</h1>

Kubernetes follows the
<a href="https://github.com/cncf/foundation/blob/master/code-of-conduct.md">CNCF Code of Conduct</a>.
The text of the CNCF CoC is replicated below, as of
<a href="https://github.com/cncf/foundation/blob/214585e24aab747fb85c2ea44fbf4a2442e30de6/code-of-conduct.md">commit 214585e</a>.
If you notice that this is out of date, please
<a href="https://github.com/kubernetes/website/issues/new">file an issue</a>.

If you notice a violation of the Code of Conduct at an event or meeting, in
Slack, or in another communication mechanism, reach out to
the <a href="https://git.k8s.io/community/committee-code-of-conduct">Kubernetes Code of Conduct Committee</a>. 
You can reach us by email at <a href="mailto:conduct@kubernetes.io">conduct@kubernetes.io</a>.
Your anonymity will be protected.

</div>
```

## Blackfriday

```html
<p>This is some <strong>HTML</strong> in a DIV block:</p>

<div class="community_main">
<h1>Kubernetes Community Code of Conduct</h1>

Kubernetes follows the
<a href="https://github.com/cncf/foundation/blob/master/code-of-conduct.md">CNCF Code of Conduct</a>.
The text of the CNCF CoC is replicated below, as of
<a href="https://github.com/cncf/foundation/blob/214585e24aab747fb85c2ea44fbf4a2442e30de6/code-of-conduct.md">commit 214585e</a>.
If you notice that this is out of date, please
<a href="https://github.com/kubernetes/website/issues/new">file an issue</a>.

If you notice a violation of the Code of Conduct at an event or meeting, in
Slack, or in another communication mechanism, reach out to
the <a href="https://git.k8s.io/community/committee-code-of-conduct">Kubernetes Code of Conduct Committee</a>. 
You can reach us by email at <a href="mailto:conduct@kubernetes.io">conduct@kubernetes.io</a>.
Your anonymity will be protected.

</div>
```

## Goldmark

```html
<p>This is some <strong>HTML</strong> in a DIV block:</p>
<div class="community_main">
<h1>Kubernetes Community Code of Conduct</h1>
<p>Kubernetes follows the
<a href="https://github.com/cncf/foundation/blob/master/code-of-conduct.md">CNCF Code of Conduct</a>.
The text of the CNCF CoC is replicated below, as of
<a href="https://github.com/cncf/foundation/blob/214585e24aab747fb85c2ea44fbf4a2442e30de6/code-of-conduct.md">commit 214585e</a>.
If you notice that this is out of date, please
<a href="https://github.com/kubernetes/website/issues/new">file an issue</a>.</p>
<p>If you notice a violation of the Code of Conduct at an event or meeting, in
Slack, or in another communication mechanism, reach out to
the <a href="https://git.k8s.io/community/committee-code-of-conduct">Kubernetes Code of Conduct Committee</a>.
You can reach us by email at <a href="mailto:conduct@kubernetes.io"><a href="mailto:conduct@kubernetes.io">conduct@kubernetes.io</a></a>.
Your anonymity will be protected.</p>
</div>
```

/cc @zacharysarah

**Comment by yuin** [comment]
CommonMark defines detailed rules for HTMLs ( [HTML blocks](https://spec.commonmark.org/0.29/#html-blocks), [Raw HTML](https://spec.commonmark.org/0.29/#raw-html) ).

CommonMark aims to make markdown unambiguously and offer compatibilities among markdown parsers. So I'm not willing to add built-in options that busted up the compatibilities of CommonMark(markdown).

I would like to recommend that you(or kubernetes project members) implement this as an extension. I also would like to recommend that you define **detailed** rules for your HTML elements parsing. Most of markdown parsers that does not get compliance with CommonMark does not document about HTML parsing, thus users probably take a lot of trial and error. It is very painful experience.

**Comment by bep** [comment]
Thanks for the input, now I understand better.

>Start condition: line begins the string < or </ followed by one of the strings (case-insensitive) address, article, aside, base, basefont, blockquote, body, caption, center, col, colgroup, dd, details, dialog, dir, div, dl, dt, fieldset, figcaption, figure, footer, form, frame, frameset, h1, h2, h3, h4, h5, h6, head, header, hr, html, iframe, legend, li, link, main, menu, menuitem, nav, noframes, ol, optgroup, option, p, param, section, source, summary, table, tbody, td, tfoot, th, thead, title, tr, track, ul, followed by whitespace, the end of the line, the string >, or the string />.
End condition: line is followed by a blank line.

If I remove the blank lines in the example above, it works as expected. I have no ambition (or time) to maintain some HTML parser extension ... I rather find a way to remove newlines in those blocks ...

Thanks again!
