### ISSUE TITLE
Option to render image for lazy loading

### ISSUE THREAD

**Issue by movsb** [yuin/goldmark#130]
I see that the default HTML renderer currently renders images with tag `<img src="`, this is compliant with CommonMark spec ( I've read the whole spec).

What I want to do is render them as `<img data-src"` for lazy loading. Also, It'll be better if the renderer can have a callback set which calls my size-calculation function to get the dimension of the image, so images with dimension (attributed as `style="width: 1px; height: 2px;"`) will be properly placed before they're loaded and won't break the page flow.

And, I don't think I should write a new renderer. So I'm here to get your suggestions.

Thanks.

**Comment by yuin** [comment]
To keep goldmark core simple, It should be implemented as an extension.
So I recommend that you write a new renderer.

**Comment by movsb** [comment]
Thanks. I just found this for a good demo to write an extension.

<https://github.com/mdigger/goldmark-images>
