### ISSUE TITLE
How to parse custom syntax that conflicts with link syntax

### ISSUE THREAD

**Issue by jschaf** [yuin/goldmark#132]
Hi there, I'm a huge fan of the library and the extensibility.  I've written a few personal extensions (https://github.com/jschaf/b2/tree/master/pkg/markdown/mdext) so I'm reasonably familiar with the parsing model.

I'm having trouble figuring out how to write my own extension for [Pandoc-style citations](https://pandoc.org/MANUAL.html#citations) like `Blah blah [@doe99, pp. 33-35, 38-39 and *passim*].` The main trouble is that the citation syntax overrides the link syntax (they both use brackets), so I can't use an inline parser.  Here's the approaches I've tried so far:

- Inline parser: if I set the priority for Citation parser lower than the Link parser, then links won't parse because the citation parser consumes the `[` and `]`. There's not a way to backtrack, so I can't retry with a link parser if the brackets belong to a link instead of a citation.

- ParagraphTransformer - it seems paragraph transformer is limited to manipulation of lines and adding block elements. Goldmark panics if I add inline elements to the paragraph. This makes sense but means I don't think I can use a ParagraphTransformer.

Some things I'm considering:

- Copying the complete contents of the link parser and adding citation logic there. I'd prefer to avoid doing this.
- Use an AST transformer. This is the best option I see.

I'd like to hear your thoughts for the best way to go about extending Goldmark to parse citations.

**Comment by yuin** [comment]
`InlineParser` should work.

Footnote built-in extension use `[` as a trigger charater, but it works together with the Link parser.

**Comment by jschaf** [comment]
> Footnote built-in extension uses [ as a trigger charater, but it works together with the Link parser.

I think the footnote parser works as an inline parser because a footnote is always on 1 line. That means you can look-ahead to see if the bracket indicates a footnote parser or not. If it's not, then the footnote parser won't consume the `[`

A citation might be spread across multiple lines, so we don't always know if it's a link or a citation from the current line. 

```md
foo [some text
@reference, pp. 30] more text
```

**Comment by yuin** [comment]
> I think the footnote parser works as an inline parser because a footnote is always on 1 line.

No. goldmark does not change behaviour about inline parsers depending on single line or not.

[BlockReader](https://github.com/yuin/goldmark/blob/master/text/reader.go#L247) can read multiple lines. Parser **always** restores position if an inline parser returns nil even if the parser have read multiple lines.

https://github.com/yuin/goldmark/blob/master/parser/parser.go#L1167
