### ISSUE TITLE
Proposal: == for the <mark> highlight element

### ISSUE THREAD

**Issue by loup-brun** [yuin/goldmark#135]
I’m adding the suggestion of the `==` fence for the [HTML `<mark>` element](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-mark-element).

**Example:**

```markdown
I would like to ==highlight a passage==
without having to type the <mark> tag.
```

The topic has been discussed in the past on this [Commonmark thread](https://talk.commonmark.org/t/highlighting-text-with-the-mark-element/840), however with no apparent outcome.

The double equal signe `==` appears to be a simple, yet preferred syntax.

This syntax is supported by some Markdown editors, such as [Typora](https://typora.io/), [iA Writer](https://ia.net/writer) (see [this update](https://ia.net/writer/blog/new-pdf-preview-better-web-publishing-improved-editing)) or the [Remarkable renderer](https://github.com/jonschlinkert/remarkable/tree/dev#syntax-extensions).

I’m not familiar with Go, but I believe this implementation would be similar to the strikethrough extension.

**Comment by yuin** [comment]
I'm not willing to add more extensions to the core repository.
This functionality should be implemented as an extension in different repository.

**Comment by jlelse** [comment]
@loup-brun If you still need this feature, I created a Go module for it: https://jlel.se/gmmark

**Comment by loup-brun** [comment]
Thanks @jlelse! 😊
