### ISSUE TITLE
Tutorial on advanced usage

### ISSUE THREAD

**Issue by pjebs** [yuin/goldmark#137]
Is there any tutorials on advanced usage of this package anywhere?

For example if I want to create a "custom" syntax or key combination to implement for example underlining of text.

eg `___SAMPLE___` => underline  (tripple underscrore)

**Comment by yuin** [comment]
> Is there any tutorials on advanced usage of this package anywhere?

I'm afraid to say, no.

> `___SAMPLE___` => underline (tripple underscrore)

This conflicts with emphasis syntax.

**Comment by pjebs** [comment]
Okay let's say I want to use this pattern instead: `&&&` instead. How would I implement that?

Once I learn how to do more advanced stuff, I'll provide some PRs with a tutorial. Perhaps in the repositories "wiki" section.

**Comment by yuin** [comment]
`parser/emphasis.go` is helpful for you.
