### ISSUE TITLE
Rendering back to markdown text?

### ISSUE THREAD

**Issue by jcorbin** [yuin/goldmark#142]
Is there any renderer implemented to round trip an AST ( say after some transformation ) back to markdown text? Maybe at least a well known 3rd party renderer implementation?

If not, I'll probably end up implementing one myself ( just as soon as I switch off blackfriday, which also lacks such a capability, in addition to its other issues... )

Basically, if you're trying to build some sort of markdown "middleware" application, say a tool to help organize notes, a journal, or some other semi-structured markdown store, you have very little interest in rendering html; but you do want to do a whole lot of AST load, manipulate, and save.

**Comment by yuin** [comment]
#119
