### ISSUE TITLE
Footnote After Link Parsing Error

### ISSUE THREAD

**Issue by theory** [yuin/goldmark#143]
The link parser seems a little confused by a footnote immediately following a brackets-only link. Sample Markdown:

``` markdown
Visit [Foo][^1].

  [Foo]: https://example.com/
  [^1]: But not really
```

Expected HTML:

``` html
<p>Visit <a href="https://example.com/">Foo</a><sup id="fnref:1"><a href="#fn:1" class="footnote-ref" role="doc-noteref">1</a></sup>.</p>
```

Actual HTML:

``` html
<p>Visit [Foo]<sup id="fnref:1"><a href="#fn:1" class="footnote-ref" role="doc-noteref">1</a></sup>.</p>
```

**Comment by yuin** [comment]
CommonMark does not include footnotes in its spec, but your example seems conflict with [link reference syntax](https://spec.commonmark.org/0.29/#example-523)

"Expected" is **your** expected, is not by spec.

markdown-it (is based on CommonMark and has a footnote extension) shows [same result](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22Visit%20%5BFoo%5D%5B%5E1%5D.%5Cn%5Cn%20%20%5BFoo%5D%3A%20https%3A%2F%2Fexample.com%2F%5Cn%20%20%5B%5E1%5D%3A%20But%20not%20really%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D) as goldmark.

You seems a Hugo user and used blackfriday that is **not** CommonMark compliant.
I think it is hard to be consistent your expectation and CommonMark spec.
Anyway, footnotes itself conflict with CommonMark spec ;)

**Comment by theory** [comment]
Huh. So the plugins are applied *after* the markdown pass, rather than before. This surprises me a bit, since I would think that "footnotes conflict with the CommonMark spec" suggests to me that one would want to convert non-compliant additional features like footnotes first, so they can then be HTML to be ignored by the core parser. Of course, that conflicts with the mode that disallows HTML I guess. Pity.

**Comment by yuin** [comment]
From CommonMark spec aspect, [this](https://spec.commonmark.org/0.29/#example-567) CommonMark spec:

```
[foo][bar][baz]

[baz]: /url1
[foo]: /url2
```

rendered as

```
<p>[foo]<a href="/url1">bar</a></p>
```

This seems to be consistent with 

```
Visit [Foo][^1].

  [Foo]: https://example.com/
  [^1]: But not really
```

```
<p>Visit [Foo]<sup id="fnref:1"><a href="#fn:1" class="footnote-ref" role="doc-noteref">1</a></sup>.</p>
```

> Here [foo] is not parsed as a shortcut reference, because it is followed by a link label (even though [bar] is not defined)

**Comment by theory** [comment]
I assume that's because the parser doesn't know that `[^` is syntactically distinct from a link indicator, since the spec, I presume, does not disallows the use of `^` or any other character at the start of a link shortcut.

The incompatibilities between CommonMark and Markdown will never not grate on my aesthetic. This is a prime example; [Markdown](https://daringfireball.net/projects/markdown/dingus) renders the `[foo][bar][baz]` example as:

``` html
<p><a href="/url2">foo</a>[bar]<a href="/url1">baz</a></p>
```

**Comment by yuin** [comment]
You are right.

If footnotes is in CommonMark spec and some rules are defined, we can avoid this behavior by looking ahead `^` in `LinkParser` .  Footnotes are just an exntesion for now, `LinkParser` does not know about footnotes.

Yeah, Markdown incompatibilities is like a hell. I do not think that CommonMark is good specification, but it is already used by famous services like Github and Stackoverflow. I believe CommonMark will be increase its share than original Markdown.

**Comment by theory** [comment]
Perhaps I should post this report to the common mark spec; where would be a good place to do that?

**Comment by yuin** [comment]
https://talk.commonmark.org/t/footnote-extensions-vs-link-reference-definition/2571

**Comment by theory** [comment]
Started a conversation [here](https://talk.commonmark.org/t/shortcut-link-questions/3582?u=theory).
