### ISSUE TITLE
Typographer regression

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#153]
I have a failing test case pulling in the latest Goldmark which looks like a regression.

```bash
      container:
              "<custom-element>\n    <div>This will be \"slotted\" into the custom element.</div>\n</custom-element>\n"
            want:
              "<p><custom-element>\n<div>This will be &ldquo;slotted&rdquo; into the custom element.</div>\n</custom-element></p>\n"
```

https://travis-ci.org/github/gohugoio/hugo/builds/725820184

If it's not obvious, I'll try to create a standalone program that triggers this.

**Comment by yuin** [comment]
This is not a regression.

[Commonmark spec]https://spec.commonmark.org/0.29/#html-block) says:

> 6. Start condition: line begins the string < or </ followed by one of the strings (case-insensitive) address, article, aside, base, basefont, blockquote, body, caption, center, col, colgroup, dd, details, dialog, dir, div, dl, dt, fieldset, figcaption, figure, footer, form, frame, frameset, h1, h2, h3, h4, h5, h6, head, header, hr, html, iframe, legend, li, link, main, menu, menuitem, nav, noframes, ol, optgroup, option, p, param, section, source, summary, table, tbody, td, tfoot, th, thead, title, tr, track, ul, followed by whitespace, the end of the line, the string >, or the string />.
End condition: line is followed by a blank line.

Your example will be parsed as a single HTML Block element because no blank lines there after `<custom-element>`.
