### ISSUE TITLE
Linkify extension differs from the GFM spec

### ISSUE THREAD

**Issue by GHSam** [yuin/goldmark#154]
I'm using goldmark v1.2.1 with the Linkify extension. With:

    http://example.com/foo_bar,

the trailing comma is included in the link which appears to differ from the [GFM spec](https://github.github.com/gfm/#extended-autolink-path-validation).

Also with:

    http://example.com/foo_bar..

goldmark includes the second to last . in the link whereas GitHub excludes both. I don't think the spec mentions what happens if there's multiple trailing punctuation but GitHub seems to exclude all trailing punctuation even if repeated or mixed.

And with:

    (http://example.com/).

the trailing ) is included whereas GitHub excludes it. Again the spec doesn't appear to mention what happens with trailing ) if followed by punctuation but it does differ from GitHub.

There's a couple of others that differ between GitHub and goldmark but don't appear to be defined at all in the spec: 

    'Example http://example.com/'

includes the trailing single quote (same with double quotes) whereas GitHub excludes it and:

    http://example.com:8000

doesn't include the port number whereas GitHub includes it.

**Comment by yuin** [comment]
Linkify extension is implemented by **spec**, not implementation.

As [Readme](https://github.com/yuin/goldmark#linkify-extension) says, you can override linkify patterns via options for corner cases.

**Comment by GHSam** [comment]
I thought Linkify was supposed to follow the GFM spec which says:

> Trailing punctuation (specifically, ?, !, ., ,, :, *, _, and ~) will not be considered part of the autolink, though they may be included in the interior of the link

whereas goldmark includes the trailing comma in:

     http://example.com/foo_bar,

The second one is more ambiguous as the spec doesn't explicitly say if should be exclude repeated trailing punctuation or just single but as GitHub excludes repeated trailing punctuation and the spec is based on GitHub markdown should the ambiguity not follow their implementation?

The 3rd one is very ambiguous in the GFM spec as depends if trailing punctuation should be removed before considering links that end with ). Removing punctuation is before trailing ) in the spec so could be how it's supposed to be interpreted but it doesn't say explicitly.
