### ISSUE TITLE
Question: extension for internal links using wiki-like syntax

### ISSUE THREAD

**Issue by dncohen** [yuin/goldmark#157]
My limited experience with goldmark is great so far.  Many thanks!

I'm considering to write an extension allowing one part of a document to link to another.  Something like:

```
# Section A
blah blah blah...
...

# Section B
See [[Section A]] for more info.
```

When rendered, section b would include something like
```
See <a href="#section-a">Section A</a>...
```

I'm hoping you can save me time.  First, does such an extension already exist?  If not, what's a good extension to emulate?

I'm imagining that I need to inspect the AST to get the section ids and titles.  Then in a second pass parse out the `[[...]]` and render them as links.  Am I thinking about this the correct way?

**Comment by dncohen** [comment]
Quick update.  I think I've figured out the basics.  I have an inline parser that looks for "[[something]]".  When it matches, it inserts an ast.Link into the AST.  Later, during AST transform, it walks all headers.  If the header text matches the "something", it transforms the link destination to be the header id.

[My code](https://src.d10.dev/tome/artifact?udc=1&name=cbffeeb6c742ea5d) needs work, no doubt. I'm open to any advice if there's a better/cleaner way.

Thanks again for contributing goldmark!

**Comment by tomcam** [comment]
dcohen, you can just use standard HTML-style anchors. This should apply to
what you want:

https://vuepressbook.com/tutorial/tutorial2.html#creating-links

**Comment by yuin** [comment]
@dncohen , Sorry for late response.

> I have an inline parser that looks for "[[something]]". When it matches, it inserts an ast.Link into the AST. Later, during AST transform, it walks all headers. If the header text matches the "something", it transforms the link destination to be the header id.

Great, I think that's OK. 

Some concerns:

1. This may conflict with CommonMark shortlink syntax.
    As you already know, your inline parser must take precedence over the built-in link parser.
2. This implementation do not allow nesting label like `[[*Section A*]]` .
    If you want to nest inline syntax, you have to implement more complex logics.
   `parser/link.go` implements it. Or you may be able to use delimiter helper functions as you can see in `parser/emphasis.go` .

**Comment by LeeSanity** [comment]
@dncohen appreciated for your job !  have you finished this extension?

**Comment by 13rac1** [comment]
@LeeSanity I separately implemented this based on another project https://github.com/13rac1/goldmark-wikilink
