### ISSUE TITLE
feature request - tag v1.2.2 to highlight emoji support on pkg.go.dev

### ISSUE THREAD

**Issue by julieqiu** [yuin/goldmark#158]
When looking at the README at https://pkg.go.dev/mod/github.com/yuin/goldmark, it's not clear that goldmark provides emoji support. This is because the README shown is the one at v1.2.1 (currently the latest version), and [documentation about emoji support](https://github.com/yuin/goldmark/commit/d102aef53ca3d50a7236935c2197a377186cecc6) was added after v1.2.1 was tagged.

It would be helpful to know about this feature when browsing goldmark on pkg.go.dev, especially given the [upcoming pkg.go.dev redesign](https://github.com/golang/go/issues/41586), where README will be the first section shown on https://pkg.go.dev/github.com/yuin/goldmark.

**Comment by yuin** [comment]
[Extensions](https://github.com/yuin/goldmark#extensions) section is just a curated list of the external extensions. 

So these extensions are not certified to work with certain goldmark versions.
