### ISSUE TITLE
help go build signal: killed

### ISSUE THREAD

**Issue by exfly** [yuin/goldmark#159]
go build -v -gcflags=all="-N -l" -o main.go

github.com/casbin/casbin/v2/util
go build github.com/yuin/goldmark/util: /home/vagrant/.goenv/versions/1.14.6/pkg/tool/linux_amd64/compile: signal: killed

any idea for this？

**Comment by yuin** [comment]
This may be a bug in Go compiler.
You can use newer versions of Go compiler(1.15.x).

**Comment by optiman** [comment]
For anyone encountering this in the future - it's just a generic error when there is not enough RAM.
