### ISSUE TITLE
What is the best way to add target & other attributes to anchors?

### ISSUE THREAD

**Issue by jjude** [yuin/goldmark#160]
This is not an issue but question. I want to add `target="_blank"` and `utm` (marketing) strings to all anchor links in a markdown. What is the best way to achieve this? Are there any examples?

_I looked into both AST & parser. Not sure if this needs to be done in parser or in AST. Any pointers to start will help._

Thanks.

**Comment by yuin** [comment]
`ASTTransformer` should do the job.  Example: [gitea](https://github.com/go-gitea/gitea/blob/814ca9ffea229f55f1f69b34d9a7f84054115669/modules/markup/markdown/goldmark.go#L110)
