### ISSUE TITLE
feature request: allow users to configure custom prefix to footnote anchors

### ISSUE THREAD

**Issue by shaform** [yuin/goldmark#161]
Please answer the following before submitting your issue:

1. What version of goldmark are you using? : 
  The latest commit on master branch: https://github.com/yuin/goldmark/commit/da9729d1345128edf7c0a411b0912b61582f915b.
2. What version of Go are you using? : 
  1.15.5
3. What operating system and processor architecture are you using? :
  Ubuntu 20.04 amd64
4. What did you do? :
  I would like to configure `fn_id_prefix`, which can be used to add custom prefix to footnote anchors as described in https://michelf.ca/projects/php-markdown/configuration/.
5. What did you expect to see? :
  A custom prefix should be added to footnote's anchor link.
6. What did you see instead? :
  No custom prefix can be configured.
7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?:
  Yes, the official renderer for footnote extension is PHP Markdown, and they do allow configuration of a custom prefix as described in https://michelf.ca/projects/php-markdown/configuration/.
8. (Feature request only): Why you can not implement it as an extension?:
    Because the footnote extension is officially included in the goldmark package, so it makes sense to directly update it instead of creating another extension package.

**Comment by GitBash-ux** [comment]
git@github.com:yuin/goldmark.git
