### ISSUE TITLE
OSS-Fuzz Integration Request

### ISSUE THREAD

**Issue by TheCrott** [yuin/goldmark#162]
Hi maintainers @yuin 

I would like to integrate the project into [OSS-fuzz](https://github.com/google/oss-fuzz). This is a free service by Google where they perform continuous fuzzing of open-source projects used by industry and with the only expectation that maintainers of the project will patch the bugs found by OSS-Fuzz.

If you are interested in this, could you please provide me with an email address that will be receiving the bug reports?

Here is the link to the integration: [Goldmark OSS-Fuzz Integration](https://github.com/google/oss-fuzz/pull/4734)

**Comment by yuin** [comment]
My email address can find in [my profile page](https://github.com/yuin).

**Comment by TheCrott** [comment]
Do you know any organization/projects/applications that use goldmark?

**Comment by yuin** [comment]
Hugo, gitea, golang.org/x/tools/present, go.pkg.dev and [many go projects](https://pkg.go.dev/github.com/yuin/goldmark?tab=importedby) uses goldmark.
