### ISSUE TITLE
Escaped pipe symbols in GitHub Flavored Markdown tables render with the escaping backslash

### ISSUE THREAD

**Issue by ianh** [yuin/goldmark#164]
**What version of goldmark are you using?**
git commit hash da9729d1345128edf7c0a411b0912b61582f915b (fetched using `go get`)

**What version of Go are you using?**
go version go1.13.4 darwin/amd64

**What operating system and processor architecture are you using?**
macOS 10.14.6, x86_64

**What did you do?**
Using the GitHub Flavored Markdown extension, rendered a table like this, with a pipe character escaped using a backslash:
```
| |
| --- |
| \| |
```

**What did you expect to see?**
A pipe character (`|`), as specified here: https://github.github.com/gfm/#tables-extension-.  This is how GitHub renders the table:

| |
| --- |
| \| |

**What did you see instead?**
In goldmark, the backslash is rendered too: (`\|`).

**Comment by yuin** [comment]
I can not reproduce this. Please submit your go code.

**Comment by ianh** [comment]
My apologies, I wrote the example incorrectly.  The \| is supposed to have backticks around it:

```
| |
| --- |
| `\|` |
```

Here's how it renders in GitHub:

| |
| --- |
| `\|` |

But running the following code:
```go
package main

import (
    "github.com/yuin/goldmark"
    "github.com/yuin/goldmark/extension"
	"os"
)

func main() {
	goldmark.New(goldmark.WithExtensions(extension.GFM)).Convert([]byte("| |\n| --- |\n| `\|` |"), os.Stdout)
}
```
produces output with a backslash in it:
```
<table>
<thead>
<tr>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td><code>\|</code></td>
</tr>
</tbody>
</table>
```

**Comment by eblechschmidt** [comment]
I'm having the same issue when testing example 200 of gfm spec (https://github.github.com/gfm/#example-200).

**Comment by eblechschmidt** [comment]
Thanks for the quick fix. Now my tests are passing.
