### ISSUE TITLE
Inconsistecy when dealing with escaped pipe in gfm examle 200

### ISSUE THREAD

**Issue by eblechschmidt** [yuin/goldmark#179]
1. What version of goldmark are you using? : ` 1.3.1`
2. What version of Go are you using? : `go1.15.6 windows/amd64`
3. What operating system and processor architecture are you using? : `go1.15.6 windows/amd64`
4. What did you do? : Parsed example 200 of gfm (https://github.github.com/gfm/#example-200)
```go
	src := []byte("| f\\|oo       |\n| ----------- |\n| b `\\|` az   |\n| b **\\|** im |\n")
	md := goldmark.New(goldmark.WithExtensions(extension.GFM))
	r := text.NewReader(src)
	d := md.Parser().Parse(r)
	d.Dump(src, 0)
```
5. What did you expect to see? : 

I expected only one ast.Text child of ast.CodeSpan that also contains the escape character as it is for example in the ast.Emphasis. From what I understand you are unescaping while rendering/writing to html. Additionally the Dump() function does not dump the content of the first as.Text child of ast.CodeSpan (I guess that is due to the fact that the end point of the segment is not set correctly).

6. What did you see instead? :

The ast.Text child of ast.CodeSpan does not contain the escape character which makes it inconsitent to the childs of ast.TableCell or ast.Emphasis.
```
Document {
    Table {
        RawText: ""
        HasBlankPreviousLines: false
        Alignments {
            none
        }
        TableHeader {
            RawText: ""
            HasBlankPreviousLines: false
            TableCell {
                RawText: "f\|oo"
                HasBlankPreviousLines: false
                Text: "f\|oo"
            }
        }
        TableRow {
            RawText: ""
            HasBlankPreviousLines: false
            TableCell {
                RawText: "b `\|` az"
                HasBlankPreviousLines: false
                Text: "b "
                CodeSpan {
                    Text(Raw): ""
                    Text(Raw): "|"
                }
                Text: " az"
            }
        }
        TableRow {
            RawText: ""
            HasBlankPreviousLines: false
            TableCell {
                RawText: "b **\|** im"
                HasBlankPreviousLines: false
                Text: "b "
                Emphasis {
                    Level: 2
                    Text: "\|"
                }
                Text: " im"
            }
        }
    }
}
```
7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?: n/a

**Comment by eblechschmidt** [comment]
Stil valid.

**Comment by yuin** [comment]
This works as expected.
CodeSpan is a special element that ignores escape character. (see [this](https://spec.commonmark.org/dingus/?text=%60%5C%7C%60))

gfm-200 says that code span should be rendered as `<code>|</code>`. So CodeSpan should not contain an escape character.

**Comment by eblechschmidt** [comment]
I think I was not clear enough with my question. The rendering in html is correct. Nevertheless the representation in the ast does not seem consistent to me.

If you take a look at all three rows in that table they are all rendered the same (without any escape characters) so I would expect the ast to respresent the same which it does not.
```
<th>f|oo</th>
<td>b <code>|</code> az</td>
<td>b <strong>|</strong> im</td>
```

For me this has to do with the fact that escaping is done in goldmark while rendering (where you raw write code spans and escape wirte emphasis e.g.) and not during parsing which I think a bit strange because that means every implementation of a new renderer has to know when escaping is necessarry. If you take a look at [this](https://spec.commonmark.org/dingus/?text=**\\|**#result-ast) in the ast section it does not have any escape characters present in the ast. I guess that is the reason why you treat the escape character in a code span in a table (gfm 200) diffrently (remove it during parsing) from e.g. the emphasis (remove it during rendering to html).
