### ISSUE TITLE
API being too complex

### ISSUE THREAD

**Issue by SeanTolstoyevski** [yuin/goldmark#181]
```
md := goldmark.New(
          goldmark.WithExtensions(extension.GFM),
          goldmark.WithParserOptions(
              parser.WithAutoHeadingID(),
          ),
          goldmark.WithRendererOptions(
              html.WithHardWraps(),
              html.WithXHTML(),
          ),
      )
```

It's a very different style of code from common Go modules.

maybe something like this would be better?

```
type Options struct {
WithExtensions: []typeofextension{x, y, z}
WithParserOptions: []typeofparser{x, y, []othertype{x, y,z}}

...
}
md := goldmark.New(Options)

...

}
```

  Am I just having trouble using it?

**Comment by moorereason** [comment]
Embrace it.  :smile:  Learn more about this approach and its advantages [from a talk by Dave Cheney](https://dave.cheney.net/2016/11/13/do-not-fear-first-class-functions).

**Comment by mickael-menu** [comment]
Functional options seem pretty common nowadays in Go projects, personally I like it.

**Comment by SeanTolstoyevski** [comment]
I do not know.
If there is nothing you can do about it, I will close the issue.

Thank you for your answers.
