### ISSUE TITLE
Linkify extension doesn't match hosts that start with single-letter domain label

### ISSUE THREAD

**Issue by moorereason** [yuin/goldmark#190]
Google's **g.page** hostname is not being matched by the Linkify extension.

Example rendering by Github in this issue editor:  https://g.page/foo

Originally [reported by a Hugo user](https://github.com/gohugoio/hugo/issues/8143), but this is an issue with goldmark.

### Questionaire:

- [x] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).
    - [x] **Extensions(Autolink without `<` `>`, Table, etc) are not part of CommonMark spec.** You should confirm your output is different from other official renderers correspond with an extension.
- [x] **goldmark is not dedicated for Hugo**. If you are Hugo user and your issue was raised by your experience in Hugo, **you should consider create issue at Hugo repository at first** .

**1. What version of goldmark are you using? :**

master (c4b3054802054bacb6445f3af7ce2d0fbbaaea1f)

**2. What version of Go are you using? :**

go1.16rc1
 
**3. What operating system and processor architecture are you using? :**

linux/amd64

**4. What did you do? :** 

```diff
diff --git a/extension/_test/linkify.txt b/extension/_test/linkify.txt
index d619a8b..134f52b 100644
--- a/extension/_test/linkify.txt
+++ b/extension/_test/linkify.txt
@@ -169,3 +169,11 @@ http://server.intranet.acme.com:1313
 //- - - - - - - - -//
 <p><a href="http://server.intranet.acme.com:1313">http://server.intranet.acme.com:1313</a></p>
 //= = = = = = = = = = = = = = = = = = = = = = = =//
+
+
+17
+//- - - - - - - - -//
+https://g.page/foo
+//- - - - - - - - -//
+<p><a href="https://g.page/foo">https://g.page/foo</a></p>
+//= = = = = = = = = = = = = = = = = = = = = = = =//
```
**5. What did you expect to see? :**

passing test

**6. What did you see instead? :**

```
--- FAIL: TestLinkify (0.00s)
    testutil.go:176: ============= case 17 ================
        Markdown:
        -----------
        https://g.page/foo

        Expected:
        ----------
        <p><a href="https://g.page/foo">https://g.page/foo</a></p>

        Actual
        ---------
        <p>https://g.page/foo</p>
```

**7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?:**

Linkify extension not part of CommonMark spec.

**Comment by cmosetick** [comment]
@moorereason Thank you for chasing this rendering issue to Linkify extension!
I guessed a while back that goldmark was the source of the single character TLD issue, but was not able to find the actual source at the time. So I just created the issue in the hugo issue tracker as a starting point.
