### ISSUE TITLE
Pipe character inside code span can terminate table

### ISSUE THREAD

**Issue by jdkato** [yuin/goldmark#194]
Using `goldmark.WithExtensions(extension.GFM)` with the following Markdown snippet 

```markdown
| Table | Table |
|-------|-------|
| Word  | `Notword|` |
```
results in 

```html
<table>
   <thead>
      <tr>
         <th>Table</th>
         <th>Table</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td>Word</td>
         <td>`Notword</td>
      </tr>
   </tbody>
</table>
```

I think the expected result here should be

```html
<table>
   <thead>
      <tr>
         <th>Table</th>
         <th>Table</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td>Word</td>
         <td><code>Notword|</code></td>
      </tr>
   </tbody>
</table>
```

I'm using Go `go1.15.7 darwin/amd64` and Goldmark `v1.3.2`.

Thanks for your work on this library.

---

As an aside, since this isn't a topic covered in the CommonMark spec, I've included a [comparison with other libraries](https://babelmark.github.io/?text=%7C+Table+%7C+Table+%7C%0A%7C-------%7C-------%7C%0A%7C+Word++%7C+%60Notword%7C%60+%7C) and there doesn't seem to be a strong consensus: e.g., [MD4C](https://github.com/mity/md4c) (another CommonMark-compliant parser) has what I'd consider to be the "expected" output, while [`cmark-gfm`](https://github.com/github/cmark) (GitHub's library) doesn't.

**Comment by yuin** [comment]
This works as expected. CommonMark does not contain tables. As README says tables are defined in Github Flavored Markdown(GFM).
GFM defines pipe characters in code span must be escaped if you want to render it in code spans.
https://github.github.com/gfm/#example-200
