### ISSUE TITLE
Render attributes in code blocks

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#195]
I have added attribute support for markdown blocks in Hugo. Mostly this works great, and I'm in the process of adding the missing pieces.

One of them is code blocks.

For the fenced code blocks that Hugo renders (using the Goldmark Chroma extension), this was easy to add. But for those that have turned off that option, it would be cool if the default code block renderer in Goldmark also rendered the attributes.

https://github.com/gohugoio/hugo/pull/8280

**Comment by yuin** [comment]
goldmark-highlighting implements attributes for code blocks, It means attributes for code blocks can be implemented as an extension unlike for headings.

Attributes are out of scope for the CommonMark. I think that it would be better to implement attributes as an extension as far as possible.
