### ISSUE TITLE
Keep footnote backlinks with text

### ISSUE THREAD

**Issue by brief** [yuin/goldmark#196]
goldmark has [https://github.com/yuin/goldmark/discussions](Discussions) in github.
You should post only issues here. Feature requests and questions should be posted at discussions.

- [x] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).
    - [x] **Extensions(Autolink without `<` `>`, Table, etc) are not part of CommonMark spec.** You should confirm your output is different from other official renderers correspond with an extension.
- [x] **goldmark is not dedicated for Hugo**. If you are Hugo user and your issue was raised by your experience in Hugo, **you should consider create issue at Hugo repository at first** .

---

Please answer the following before submitting your issue:

1. **What version of goldmark are you using?** `1.3.2`
2. **What version of Go are you using?** `1.16`
3. **What operating system and processor architecture are you using?** `macOS Big Sur 11.3 Beta / x86_64`
4. **What did you do?**

Created a footnote, like so:

```
This is a footnote[^1]

[^1]: Roses are red, violets are blue
```

5. **What did you expect to see?**

Expected the last word of the footnote and the backlink arrow to wrap together, as follows:

```
This is a footnote¹

---

1. Roses are red, violets are
blue ↩
```

PHP Markdown Extra inserts a [non-breaking space before footnote backlinks](https://github.com/michelf/php-markdown/blob/lib/Michelf/MarkdownExtra.php#L1743) instead of a normal space. I thought this was a recent change, but it has apparently done this [since 2006](https://github.com/michelf/php-markdown/commit/2c2b637293d092c026945bbf011ff2b13e08fd5a#diff-b4817bd48283401dfe2b22afa444432b8dccb5dc50eca621c82c74dd22456befR2661).

6. **What did you see instead?**

The backlink arrow can break to a new line of its own on narrow screens:

```
This is a footnote¹

---

1. Roses are red, violets are blue
↩
```

7. **Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?** `N/A, as this is for the footnote extension.`

**Comment by yuin** [comment]
That makes sense.
