### ISSUE TITLE
Panic on simple broken commonmark with goldmark-highlighting

### ISSUE THREAD

**Issue by zeripath** [yuin/goldmark#203]
goldmark has [https://github.com/yuin/goldmark/discussions](Discussions) in github.
You should post only issues here. Feature requests and questions should be posted at discussions.

- [x] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).
    - [x] **Extensions(Autolink without `<` `>`, Table, etc) are not part of CommonMark spec.** You should confirm your output is different from other official renderers correspond with an extension.
- [x] **goldmark is not dedicated for Hugo**. If you are Hugo user and your issue was raised by your experience in Hugo, **you should consider create issue at Hugo repository at first** .

Please answer the following before submitting your issue:

1. What version of goldmark are you using? : v1.3.2
2. What version of Go are you using? : 16.1
3. What operating system and processor architecture are you using? : linux amd64
4. What did you do? : passed the following through goldmakr

<pre>
a
:	```
		a
</pre>

5. What did you expect to see? : not a panic
6. What did you see instead? : 

```
runtime error: slice bounds out of range [14:13]
	/usr/local/go/src/runtime/panic.go:116 (0x43de84)
		goPanicSliceB: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsSliceB})
	/home/andrew/src/go/gitea/vendor/github.com/yuin/goldmark/text/segment.go:48 (0xf0ecf2)
		(*Segment).Value: return append(result, buffer[t.Start:t.Stop]...)
	/home/andrew/src/go/gitea/vendor/github.com/yuin/goldmark-highlighting/highlighting.go:516 (0x119ce6e)
		(*HTMLRenderer).renderFencedCodeBlock: r.Writer.RawWrite(w, line.Value(source))
	/home/andrew/src/go/gitea/vendor/github.com/yuin/goldmark/renderer/renderer.go:166 (0xf34c47)
		(*renderer).Render.func2: s, err = f(writer, source, n, entering)
	/home/andrew/src/go/gitea/vendor/github.com/yuin/goldmark/ast/ast.go:492 (0xf11c62)
		walkHelper: status, err := walker(n, true)
	/home/andrew/src/go/gitea/vendor/github.com/yuin/goldmark/ast/ast.go:498 (0xf11d7b)
		walkHelper: if st, err := walkHelper(c, walker); err != nil || st == WalkStop {
	/home/andrew/src/go/gitea/vendor/github.com/yuin/goldmark/ast/ast.go:498 (0xf11d7b)
		walkHelper: if st, err := walkHelper(c, walker); err != nil || st == WalkStop {
	/home/andrew/src/go/gitea/vendor/github.com/yuin/goldmark/ast/ast.go:498 (0xf11d7b)
		walkHelper: if st, err := walkHelper(c, walker); err != nil || st == WalkStop {
	/home/andrew/src/go/gitea/vendor/github.com/yuin/goldmark/ast/ast.go:487 (0xf345fb)
		Walk: _, err := walkHelper(n, walker)
	/home/andrew/src/go/gitea/vendor/github.com/yuin/goldmark/renderer/renderer.go:161 (0xf3455c)
		(*renderer).Render: err := ast.Walk(n, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
	/home/andrew/src/go/gitea/vendor/github.com/yuin/goldmark/markdown.go:117 (0xf3d024)
```

7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?: yes

**Comment by yuin** [comment]
Could you create an issue in the goldmark-highlighting repository?
