### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#21]
Ref this interface:

```go
// A Markdown interface offers functions to convert Markdown text to
// a desired format.
type Markdown interface {
	// Convert interprets a UTF-8 bytes source in Markdown and write rendered
	// contents to a writer w.
	Convert(source []byte, writer io.Writer, opts ...parser.ParseOption) error

	// Parser returns a Parser that will be used for conversion.
	Parser() parser.Parser

	// SetParser sets a Parser to this object.
	SetParser(parser.Parser)

	// Parser returns a Renderer that will be used for conversion.
	Renderer() renderer.Renderer

	// SetRenderer sets a Renderer to this object.
	SetRenderer(renderer.Renderer)
}

```

With the above, I can create a `Markdown` with a custom `parser` and `renderer` (I'm not sure what the setters are for) and then run `Convert` to do the job.

A big win (ref. your benchmarks) when you have this strict separation between parse and render, is to parse once and render to every format you need. I don't see how that is possible with the current API?

**Comment by yuin** [comment]
You have getters for a `Parser` and a `Renderer` in the `Markdown` interface.

So you can parse the document to build an AST by `ast := Parser().parse(reader, opts...)` .
Once you have an AST object, you can render the AST by `Renderer().Render(writer, source, ast)` as many times as you want.

Detailed code are found [here](https://github.com/yuin/goldmark/blob/master/markdown.go#L115).

You can also create a Parser and a Renderer without the `Markdown` interface. See [here](https://github.com/yuin/goldmark/blob/master/markdown.go#L15) and [here](https://github.com/yuin/goldmark/blob/master/markdown.go#L23) .

**Comment by bep** [comment]
OK, I get it, I must have read this without my glasses on ... Thanks!
