### ISSUE TITLE
Quote marks don't close when followed by a dash [Typographer]

### ISSUE THREAD

**Issue by racingmars** [yuin/goldmark#211]
Using Goldmark 1.3.3 with Go 1.16.2 on linux/amd64.

I have enabled the tyopgrapher extension that is included with goldmark, and am rendering content which includes the following Markdown input:

`I asked where he was, to no avail ("Where were you?"---"I couldn't say").`

The quotes *mostly* translate to opening and closing quotes correctly, except the second double-quote, the one after "you?" and before the "---". It gets translated as `&quot;` instead of the expected `&rdquo;`

If I add spaces around the em-dash, `I asked where he was, to no avail ("Where were you?" --- "I couldn't say").`, then all of the quotes translate correctly as I'd expect.

I'm not sure how the typography extension logic works, but it seems like it might need to treat a dash/hyphen following a `"` the same way it treats whitespace.

**Comment by racingmars** [comment]
For the sake of stale bot... this issue is still open!

**Comment by brycewray** [comment]
Related to https://github.com/yuin/goldmark/issues/180 by any chance?
