### ISSUE TITLE
Reference-style links broken across newline

### ISSUE THREAD

**Issue by harding** [yuin/goldmark#237]
(Reviewed boilerplate checkboxes.)

Please answer the following before submitting your issue:

1. What version of goldmark are you using? : v1.4.0
2. What version of Go are you using? : go1.11.6
3. What operating system and processor architecture are you using? : Debian GNU/Linux, amd64
4. What did you do? :

```markdown
This is a [test][foo
bar] 1...2..3...

[foo bar]: /
```

5. What did you expect to see? : "This is a [test](/) 1...2..3..."

6. What did you see instead? :

![latest](https://user-images.githubusercontent.com/61096/128256623-e2a4c327-43a3-4033-b716-805253bc9b7b.png)

7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?:  Yes, https://spec.commonmark.org/dingus/?text=This%20is%20a%20%5Btest%5D%5Bfoo%0Abar%5D%201...2..3...%0A%0A%5Bfoo%20bar%5D%3A%20%2F

See also: https://spec.commonmark.org/0.30/#example-540

Bug was observed when using the latest version of Hugo.  Reported there as https://github.com/gohugoio/hugo/issues/8855 ; a maintainer there confirmed the output was unexpected and asked that I report it here.

**Comment by jmooring** [comment]
Please keep this open.

**Comment by harding** [comment]
Thank you!
