### ISSUE TITLE
Rather a question

### ISSUE THREAD

**Issue by zzwx** [yuin/goldmark#25]
Thank you for great work on this library! I've been looking for this clean implementation that works out-of-box without any patches. 

Now for a project I'm working on I need a little bit of hacking of default renderer. Would you please direct me as to where I would plug my custom rendering of a youtube auto-links. Basically I'm having them as `*ast.AutoLink` nodes. Now I'm trying to rewrite the rendering of those so that they appear in `<div>`s with the `<img>` of the youtube preview picture and `<a>` leading to the video. That's the idea.

So far I've been able to declare a custom type:

```go
// CustomGoldmarkRenderer renders specific markdown documents containing video links
type CustomGoldmarkRenderer struct {
	defaultRenderer renderer.Renderer
	file            *[]byte
}
```
which then I make implementing the Renderer interface:

```go
func (c CustomGoldmarkRenderer) Render(w io.Writer, source []byte, n ast.Node) error {
	ast.Walk(n, func(n ast.Node, entering bool) (status ast.WalkStatus, err error) {
		switch t := n.(type) {
		case *ast.AutoLink:
			url := string(t.URL(*c.file))
			matches := youTubeLinkRegex.FindAllStringSubmatch(url, -1)
			if len(matches) == 0 {
				// Or try a short link
				matches = youTubeShortLinkRegex.FindAllStringSubmatch(url, -1)
			}
			if len(matches) > 0 {
				videoID := matches[0][1] // Group 1 stands for the first (...) block
				if entering {
					fmt.Fprintf(w, `
					<div class="py-2 col-12 col-xl-3 col-lg-3 col-md-4 mb-2">
						<a href="%s" target="_blank" class="d-block h-180">
							<img class="img-fluid img-thumbnail rounded" src="%s" alt="%s"/>
						</a>
						%s`,
						url,
						"https://img.youtube.com/vi/"+videoID+"/mqdefault.jpg",
						"title",
						"titleHTML")
					return ast.WalkSkipChildren, nil
				} else {
					fmt.Fprintf(w, `</div>`)
				}
			}
		}
		return ast.WalkContinue, nil
	})
	return c.defaultRenderer.Render(w, source, n)
}
```

so that I'm able to plug my custom renderer into the `md := goldmark.New(...)` as following:

```go
	md.SetRenderer(CustomGoldmarkRenderer{
		defaultRenderer: md.Renderer(),
		file:            &file,  // Passing original source so that it becomes available in parsing function
	})

	var buf bytes.Buffer
	if err := md.Convert(file, &buf); err != nil {
		panic(err)
	}
```

Now of course what I get is simply my additional rendering of `<div>`s that I do with my walker, and then (with no surprise) the ordinary rendering is being appended to the io.Writer when `return c.defaultRenderer.Render(w, source, n)` comes into play.

Being an amateur coder in Go I can't figure out how to render the rest of the nodes **with the default way** while I do the rendering in my custom `ast.Walk(...)` call, node by node, since `return c.defaultRenderer.Render(w, source, n)` seems to be called just once for the Document node and doesn't really help me with individual nodes at all.

So, Would you be so kind to hint me where I'm wrong and which direction I would rather need to choose?

**Comment by yuin** [comment]
You can achieve this by simply implementing a `renderer.NodeRenderer` that renders `ast.AutoLink` nodes(see [here](https://github.com/yuin/goldmark/blob/master/extension/footnote.go#L188) for example).

And you can register the `renderer.NodeRenderer` like the following:

```go
	m.Renderer().AddOptions(renderer.WithNodeRenderers(
		util.Prioritized(NewYourAutoLinkRenderer(), 0),
	))
```

Note that 2nd argument for the `util.Prioritized` is a priority value. Smaller value has high priority so you can override existing AutoLinkRenderer by `0`(smallest, that means highest priority).

**Comment by zzwx** [comment]
Hi @yuin, Cool, Thank you for the hint! I think I was able to render the links with the method you explained! Now the problem is in fall-backing to regular rendering when it is **not** a youtube link.

So far my render function does the following:
```go
func (y *YoutubeHTMLRenderer) renderYoutubeLink(w util.BufWriter, source []byte, node gast.Node, entering bool) (gast.WalkStatus, error) {
	n := node.(*gast.AutoLink)
	url := string(n.URL(source))
	matches := youTubeLinkRegex.FindAllStringSubmatch(url, -1)
	if len(matches) == 0 {
		// Or try a short link
		matches = youTubeShortLinkRegex.FindAllStringSubmatch(url, -1)
	}
	if len(matches) > 0 {
		videoID := matches[0][1] // Group 1 stands for the first (...) block
		if entering {
			fmt.Fprintf(w, `
					<div class="py-2 col-12 col-xl-3 col-lg-3 col-md-4 mb-2">
						<a href="%s" target="_blank" class="d-block h-180">
							<img class="img-fluid img-thumbnail rounded" src="%s" alt="%s"/>
						</a>
						%s`,
				url,
				"https://img.youtube.com/vi/"+videoID+"/mqdefault.jpg",
				"title",
				"titleHTML")
			return gast.WalkContinue, nil
		} else {
			fmt.Fprintf(w, `</div>`)
			return gast.WalkContinue, nil
		}
	}
	return gast.WalkContinue, nil
}
```

Now the question is, what should I return back in order to say "Well, I'm not going to render this, use a low level priority rendering"?

**Comment by yuin** [comment]
I see. You have may choices.

1. Calling`parser.NewAutolinkParser()` and use it in your renderer.
2. Different approach.
    1. Define a new ast node like `ast.YoutubeAutoLink` node.
    2. Define `parser.ASTTransformer` and call `ast.Walk` in the transformer.
        1. If you find an `ast.AutoLink` node by walking the AST tree, replace it with `ast.YoutubeAutoLink` node.
    3. Define `NodeRenderer` that renders `ast.YoutubeAutoLink` nodes.

**Comment by zzwx** [comment]
Thanks for the hint! Working on it.

In a meanwhile I wonder if a WalkTryNextPrioirty is possible to implement so that if it is returned, the next in priority renderer would kick in? Of course I'm far from understanding yet how the things work, so ignore it if the idea is stupid.

**Comment by zzwx** [comment]
Hmm. Am I actually allowed to modify the tree on fly? I'm seeing some weird results. This is so far my AST transformer:

```go
func (a *youtubeLinkASTTransformer) Transform(node *gast.Document, reader text.Reader, pc parser.Context) {
	gast.Walk(node, func(n gast.Node, entering bool) (status gast.WalkStatus, err error) {
		if entering {
			return gast.WalkContinue, nil
		}
		if autoLink, ok := n.(*gast.AutoLink); ok {
			if n.Parent() != nil {
				source := reader.Source()
				url := autoLink.URL(source)
				videoID := getYoutubeID(string(url))
				if videoID != "" {
					newYoutubeLink := YoutubeLink{
						AutoLink: *autoLink,
					}
					//n.Parent().InsertAfter(n.Parent(), n, &newYoutubeLink)
					//n.Parent().AppendChild(n.Parent(), &newYoutubeLink)
					n.Parent().ReplaceChild(n.Parent(), n, &newYoutubeLink)
				}
			}
		}
		return gast.WalkContinue, nil
	})
	//node.Dump(reader.Source(), 0)
}
```

For some reason `ReplaceChild` makes two links following each other only the first one being recognized. Then the `AppendChild` gives a better result but I'm expecting AutoLink to be still in the tree, and it looks like AppendChild makes AutoLink disappear. May be I'm not getting what's going on.

Does this all look the right approach?

**Comment by yuin** [comment]
You can not remove or replace nodes in `ast.Walk` .

```go
func Walk(n Node, walker Walker) error {
	status, err := walker(n, true)
	if err != nil || status == WalkStop {
		return err
	}
	if status != WalkSkipChildren {
		for c := n.FirstChild(); c != nil; c = c.NextSibling() {
			if err := Walk(c, walker); err != nil {
				return err
			}
		}
	}
	status, err = walker(n, false)
	if err != nil || status == WalkStop {
		return err
	}
	return nil
}
```

If you remove or replace nodes in `ast.Walk`, `c = c.NextSibling` will be a `nil` . So next sibling node will no be visited by `ast.Walk`.

You should add autolinks to the certain collection when finding autolinks in `ast.Walk` and replace these nodes after calling `ast.Walk` .

**Comment by zzwx** [comment]
Makes sense! Trying! Thanks for the hint

**Comment by zzwx** [comment]
That did the trick! Thank you! I might publish it later just as an example on how to implement something like this.
