### ISSUE TITLE
Deprecate usage of `doc-endnote[s]` ARIA roles in footnote extension

### ISSUE THREAD

**Issue by schnerring** [yuin/goldmark#258]
- [x] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).
    - [ ] **Extensions(Autolink without `<` `>`, Table, etc) are not part of CommonMark spec.** You should confirm your output is different from other official renderers correspond with an extension.
- [x] **goldmark is not dedicated for Hugo**. If you are Hugo user and your issue was raised by your experience in Hugo, **you should consider create issue at Hugo repository at first** .  
See: https://github.com/gohugoio/hugo/issues/9054

---

Running Google Lighthouse on Goldmark output containing footnotes causes the following error:

```
Some ARIA parent roles must contain specific child roles to perform their intended accessibility functions.
```

Google Lighthouse now seems to adhere to [version 1.1 of the ARIA spec](https://www.w3.org/TR/dpub-aria-1.1/). The [docs regarding the error](https://web.dev/aria-required-children/?utm_source=lighthouse&utm_medium=devtools) (linked from Lighthouse) also reference version 1.1 of the spec. The spec states:

> The doc-endnote and doc-bilbioentry roles are being deprecated due to their incompatibility with the core ARIA inheritance model for roles (i.e., ARIA’s list role cannot be satisfied by list item roles in a module)

https://github.com/w3c/epubcheck/issues/1018#issuecomment-809385963 states:

> Moving forward, there will just be footnotes [`doc-footnote`], and if you want to make a list of them just wrap them in a list.

And https://github.com/w3c/epubcheck/issues/1018#issuecomment-809376951 clarifies:

> NOTE
> The doc-endnote role was designed for use as a list item, but due to clarifications in the WAI-ARIA specification, it is not valid as a child of the list role. As the doc-endnotes role already identifies a section of endnotes, authors are instead advised to use the list and listitem roles when native HTML elements cannot be used to structure the entries. The doc-footnote role can be used within each list item to identify individual notes when necessary.

My guess would be to use `doc-footnote` in place of `doc-endnote`.

**Comment by jmooring** [comment]
<https://github.com/w3c/epubcheck/issues/1018#issuecomment-945187546>

> There's an updated working draft coming soon. In it, **endnotes are implied on the immediate list item descendants of a doc-endnotes marked section and the use of doc-footnote is not allowed**. This was done to avoid the ambiguity of whether the content within the list item is a footnote or endnote.
>
> But this does make things simpler, as you can simply drop the explicit role and there's still an assumption that the list items are endnotes.

So, at some point we can eliminate the `role` attribute from the list items, but I don't know when that should happen.

**Comment by tristan957** [comment]
Happy to help move this along if possible/necessary.

**Comment by Seirdy** [comment]
@schnerring [dequelabs/axe-core](https://github.com/dequelabs/axe-core) is what power's most of Lighthouse's accessibility audits (and the a11y audits for pretty much every checker written in JavaScript). v4.4.1 of axe-core has deprecated doc-endnote, FWIW; see Lighthouse's [issue 12432](https://github.com/GoogleChrome/lighthouse/issues/12432).

Once Lighthouse bumps its axe-core dep, Lighthouse won't have that issue anymore.

**Comment by yuin** [comment]
[Version 1.1](https://www.w3.org/TR/dpub-aria-1.1/#doc-endnotes) says:

> Authors MUST NOT declare elements with the role [doc-footnote](https://www.w3.org/TR/dpub-aria-1.1/#doc-footnote) within the endnotes as it is redundant with the implied role.

So I've removed `role` attributes from footnote list items.

**Comment by tristan957** [comment]
Thanks for your work on this. Can't wait to see it in a release and get picked up by Hugo downstream :).
