### ISSUE TITLE
Add some kind of "non-rendering render hook"

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#26]
In working on adding this to Hugo, I wanted to implement ToC in a general way that we could possibly also use for other things; e.g. a "content map" with byte slice pointers (start/stop) into the **rendered content**.

I experimented by creating an extension:

https://github.com/bep/hugo/blob/goldmark2/markup/goldmark/contentmap.go#L35

But that doesn't work, as I notice that you pick up the first renderer for a given node kind.

Note that for the ToC thing (which is what Hugo has today), I can traverse the AST and build the ToC from that, but it would be really useful if could somehow register the rendered start/stop position for the different blocks; so people could do things like:

* Split content over multiple pages
* Insert ads/bylines etc.
* ...

Again, thanks for this library, it's really easy to use.

**Comment by yuin** [comment]
What you want is probably an [ASTTransformer](https://github.com/yuin/goldmark/blob/master/parser/parser.go#L519). You can add your ASTTransformer by [WithASTTransformers](https://github.com/yuin/goldmark/blob/master/parser/parser.go#L652).

The footnote extension is implemented using an ASTTransformer(see [here](https://github.com/yuin/goldmark/blob/6299e68ee5b77a17bfd94e38e154a2947748c509/extension/footnote.go#L164))

In case of ToC extension, you can use the [ast.Walk](https://github.com/yuin/goldmark/blob/master/ast/ast.go#L432) function inside an ASTTransformer to traverse heading nodes,

If I implement a ToC Extension:

1. Define an `ast.TableOfContents` block node
2. Define an ASTTransformer
    1. Allocate some collection(slice, map, or structs) to store "ToC" data.
    2. Call `ast.Walk`
        1. If find a heading node, add it to the collection.
        2. if find an `ast.TableOfContents` node, assign it to some variable.
3. Update an `ast.TableOfContents` node that was found at above by the collection.
4. Define a NodeRenderer that renders `ast.TableOfContents` node
5. Wrapped these up as an `Extender` .

**Comment by bep** [comment]
Adding the ToC to this discussion was a mistake.

What I want/need (which I also would consider to be generally very useful) is a way to map the **rendered output**, i.e.record the start/stop indices of selected blocks in the render buffer, so I could do:

```go
buf := &bytes.Buffer{}
md.Convert(ctx.Src, buf)
b := buf.Bytes()

firstHeader := b[12:32]
```

**Comment by bep** [comment]
But note that this isn't something I need right now, but it would be really cool...

**Comment by yuin** [comment]
I see. But I have never seen such functionalities in other libraries, so I can not imagine what is good APIs. Do you have any libraries in your mind that implement this functionality?
