### ISSUE TITLE
no renderhook on linkify 

### ISSUE THREAD

**Issue by swamidass** [yuin/goldmark#261]
Does it make sense to call the link render hook on linkify? Right now, it doesn't seem that goldmark does this.  This is more of a bug than a feature enhancement.

It could be argued that a new render hook is needed, but that should not be necessary. The function called by the hook should be able to identify linkified links by noting that the href equals the display text. The current problem is that there is no way to catch the event, as far as I can tell.

goldmark version: 1.4.2

**Comment by yuin** [comment]
goldmark does not have a concept like 'hook'.
You seems to confuse goldmark with Hugo.
