### ISSUE TITLE
linkify: provide option to define protocol for www extended autolinks  

### ISSUE THREAD

**Issue by jmooring** [yuin/goldmark#267]
With the linkify extension enabled, `www.example.org` renders  to:

```
<a href="http://www.example.org">www.example.org</a>
```

The protocol in the `href` attribute is hard coded to `http`:
<https://github.com/yuin/goldmark/blob/master/extension/linkify.go#L200>

This causes problems when serving the rendered markdown via `https`.

See <https://github.com/gohugoio/hugo/issues/9225#issue-1068403711>.

**Comment by yuin** [comment]
This behavior is defined by [official spec](https://github.github.com/gfm/#autolinks-extension-).

> The scheme **http** will be inserted automatically:

**Comment by jmooring** [comment]
Thank you for pointing me to spec, and thanks for goldmark!
