### ISSUE TITLE
New lines within span-level elements 

### ISSUE THREAD

**Issue by mironovalexey** [yuin/goldmark#3]
When span-level element contain new lines, its content is not treated as markdown.

Test case: https://github.com/mironovalexey/gm-test (html package).

https://github.com/mironovalexey/gm-test/blob/master/html/test.md

**Comment by yuin** [comment]
Could you explain details?

I've tried this markdown with goldmark:

```markdown

<span>This *markup* **should** be treaded as `markdown`.</span>

<span>
  
This *markup* **should** be treaded as `markdown`.

</span>

<i>And this **too**.</i>

<i>
  
And this **too**.

</i>

```

result:

```html
<p><span>This <em>markup</em> <strong>should</strong> be treaded as <code>markdown</code>.</span></p>
<span>
<p>This <em>markup</em> <strong>should</strong> be treaded as <code>markdown</code>.</p>
</span>
<p><i>And this <strong>too</strong>.</i></p>
<i>
<p>And this <strong>too</strong>.</p>
</i>
```

This seems OK.

**Comment by mironovalexey** [comment]
Sure. 

Running https://github.com/mironovalexey/gm-test/blob/master/html/run.go
on
https://github.com/mironovalexey/gm-test/blob/master/html/test.md

```
## Span level

<span>This *markup* **should** be treaded as `markdown`.</span>

<span>
  
This *markup* **should** be treaded as `markdown`.

</span>

<i>And this **too**.</i>

<i>
  
And this **too**.

</i>
```
gives
```
<h2>Span level</h2>
<p><span>This <em>markup</em> <strong>should</strong> be treaded as <code>markdown</code>.</span></p>
<span>
This *markup* **should** be treaded as `markdown`.
</span>
<p><i>And this <strong>too</strong>.</i></p>
<i>
And this **too**.
</i>
```

**Comment by yuin** [comment]
I've run https://github.com/mironovalexey/gm-test/blob/master/html/run.go
on
https://github.com/mironovalexey/gm-test/blob/master/html/test.md

but I've got

```
<h2>Span level</h2>
<p><span>This <em>markup</em> <strong>should</strong> be treaded as <code>markdown</code>.</span></p>
<span>
<p>This <em>markup</em> <strong>should</strong> be treaded as <code>markdown</code>.</p>
</span>
<p><i>And this <strong>too</strong>.</i></p>
<i>
<p>And this <strong>too</strong>.</p>
</i>
```
strange...

**Comment by mironovalexey** [comment]
```
$ go version
go version go1.12.1 linux/amd64
```
goldmark https://github.com/yuin/goldmark/commit/2988e183edbde97e8dec59a024ff685ed7d09bf0

**Comment by yuin** [comment]
```
$ go version
go version go1.12.5 windows/amd64
```

goldmark 2988e183edbde97e8dec59a024ff685ed7d09bf0

goldmark passes all commonmark spec tests. This issue is similar to [Test 137](https://spec.commonmark.org/0.29/#example-137). goldmark passes this test on my windows machine and on travis CI ([go version go1.12.5 linux/amd64](https://travis-ci.org/yuin/goldmark/jobs/532372380))

This issue may depend on environments.

**Comment by yuin** [comment]
```
$ go version
go version go1.12.1 linux/arm64
```

goldmark 2988e183edbde97e8dec59a024ff685ed7d09bf0

also renders correctly.

**Comment by mironovalexey** [comment]
This is my fault (сhecked on the wrong branch). Sorry to trouble you. I didn't know that goldmark passes all commonmark spec test (it's very impressive), so I'll check more carefully.
