### ISSUE TITLE
Colon inside ** breaks "boldness"

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#30]
```go
package main

import (
	"bytes"
	"fmt"
	"log"

	"github.com/yuin/goldmark"
)

func main() {
	content := `**Bold:**Regular`

	markdown := goldmark.New()

	var buf bytes.Buffer
	err := markdown.Convert([]byte(content), &buf)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(buf.String())
}
```

Prints:

```html
<p>**Bold:**Regular</p>
```

**Comment by 88250** [comment]
@bep The output is expected, the details described in CommonMark Spec https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis

**Comment by yuin** [comment]
@88250 Thanks for your comment about this.

@bep  As @88250 says, This is not a bug, and is compliant with CommonMark spec. You can try this [here](https://spec.commonmark.org/dingus/) (or just a github comment textarea) and will get same result. [Emphasis rules in Commonmark](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis) is complicated as hell. You can avoid this by adding spaces after right '**' like `**Bold:** Regular` .

**Comment by bep** [comment]
OK, thanks. I just got some failed test assertions in Hugo from this, so I assumed it was a bug.
