### ISSUE TITLE
typographer extension should ignore code element content

### ISSUE THREAD

**Issue by jmooring** [yuin/goldmark#308]
<details>
<summary>main.go</summary>

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/renderer/html"
)

func main() {
	md := goldmark.New(
		goldmark.WithExtensions(
			extension.Typographer,
		),
		goldmark.WithRendererOptions(
			html.WithUnsafe(),
		),
	)

	input := `<code>"foo"</code>`

	var buf bytes.Buffer
	if err := md.Convert([]byte(input), &buf); err != nil {
		panic(err)
	}

	fmt.Println(buf.String())

}
````
</details>
<br>

Desired output:

```html
<p><code>"foo"</code></p>
```

Actual output:

```html
<p><code>&ldquo;foo&rdquo;</code></p>
```

**Comment by yuin** [comment]
This works as expected.

CommonMark spec does not have handlings for specific inline HTML tags. See [Raw HTML](https://spec.commonmark.org/0.30/#raw-html) section in CommonMark spec.

[CommonMark dingus](https://spec.commonmark.org/dingus/?text=%3Ccode%3E**bold**%3C%2Fcode%3E) renders contents between `<code>` tags as markdown.

```
<code>**bold**</code>
```

```
<p><code><strong>bold</strong></code></p>
```

**Comment by jmooring** [comment]
Please re-open.

> This extension substitutes punctuations with typographic entities like [smartypants](https://daringfireball.net/projects/smartypants/).

The smartypants documentation states:

> SmartyPants does not modify characters within `<pre>`, `<code>`, `<kbd>`, or `<script>` tag blocks. Typically, these tags are used to display text where smart quotes and other “smart punctuation” would not be appropriate, such as source code or example markup.

Goldmark currently handles `<pre>` and `<script>` correctly, and should handle `<code>` and `<kbd>` in the same way.

cc: @kaushalmodi

**Comment by yuin** [comment]
'**like** smartypants' does not mean that typographer extension **is** smartypants.

`<pre>` and `<script>` are [HTML blocks ](https://spec.commonmark.org/0.30/#html-blocks) but not [Raw HTML](https://spec.commonmark.org/0.30/#raw-html) .

Thus

> Goldmark currently handles `<pre>` and `<script>` correctly, and should handle `<code>` and `<kbd>` in the same way.

is not correct.

**Comment by kaushalmodi** [comment]
@yuin Can you please separate the CommonMark spec from the Smart quotes feature? The latter feature is anyways not part of the CommonMark spec. 

If a user has `<code>"something"</code>`, they want to show that element content verbatim. (Other HTML elements in this family would be `pre`, `kbd`, `samp` and `var`.)

While I agree that CommonMark spec allows the rendering of Markdown inside `code` elements, the conversion of straight quotes to curved quotes is not governed by that spec. And so I hope that the behavior of that smart quote conversion is decided by the practical nature of the `code` and related HTML elements.

**Comment by yuin** [comment]
No.
@kaushalmodi 

Original smartypants is defined for HTMLs, but Typographer extension is defined for CommonMark. It is unnatural that CommonMark parser handles specific inline HTML elements.

Other implementation also behaves in same way about inline HTMLs.

Example: [markdown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Ccode%3E%5C%22foo%5C%22%3C%2Fcode%3E%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) 

Could you tell me CommonMark implementations that behave way you want?

**Comment by kaushalmodi** [comment]
> Could you tell me CommonMark implementations that behave way you want?

I perceive this is an oversight in the CommonMark spec .. I have put more details in https://github.com/commonmark/commonmark-spec/issues/711.

I don't understand why the CommonMark spec would allow polluting the user content which the user explicitly marked as "dont' touch"! The `<code>` block is especially meant for that.

---

This issue was raised from a practical issue I noticed here:

![image](https://user-images.githubusercontent.com/3578197/169710615-53477106-959c-4cb3-8f18-abf527afe9b2.png)

If a user reading my blog copied that rendered portion with the curved quotes, they will get a Nim compilation failure!

I had expected the smart quoting to not touch the `<code>` block. But now that it has, it made my code block invalid. 

---

While I would hope this to be properly fixed in CommonMark, it would be great if at least the smart quotations can leave out the code-related HTML elements like `<code>`.

**Comment by yuin** [comment]
Good action 👍 

goldmark is a CommonMark parser. If commonmark/commonmark-spec#711 is accepted, I will implement it as defined.

**Comment by kaushalmodi** [comment]
@yuin I would appreciate your opinion in that issue please.

Putting the current version of the spec aside, does my explanation [above](https://github.com/yuin/goldmark/issues/308#issuecomment-1133951929) make sense to you?

**Comment by yuin** [comment]
> Putting the current version of the spec aside, does my explanation https://github.com/yuin/goldmark/issues/308#issuecomment-1133951929 make sense to you?

I'm a neutral about this. From the point of view of CommoMark related product users, it makes sense. But the point of view of CommoMark library author, this is not straightforward for your requirements.

It would be better solutions that spec defines attributes for backticks like `` `my code`{class=foo} ``
