### ISSUE TITLE
Rendering of external links in safe mode

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#34]
I've now merged in Goldmark as the default Markdown handler in Hugo and it works great.

I have set `unsafe=false` as the default, and that works mostly as expected.

But the rendering of external links comes as a surprise on most people, I think.

```
[Google Search!](https://google.com/)
```
=>

[Google Search!](<a href="https://google.com/">https://google.com/</a>)

So, the security motivation behind the above is maybe to prevent fake linking? But when the end result is that most people configure it to be unsafe just to get proper links, I think that makes the net security much less.

https://github.com/gohugoio/hugoThemesSite/issues/67

**Comment by yuin** [comment]
Thanks for reporting this. This is not related to the safe mode. The link parser parses link and images.  Images has prefix `'!'` .  This bug is related to wrong handling of `'!'`.
