### ISSUE TITLE
html.WithHardWraps() is not working

### ISSUE THREAD

**Issue by ivanjaros** [yuin/goldmark#356]
`html.WithHardWraps()` sets the `const optHardWraps renderer.OptionName = "HardWraps"` config option but is is not utilized anywhere. Hence new lines are not translated into `<br/>`.

**Comment by yuin** [comment]
You seem misunderstanding source codes.
`WithHardWraps` works correctly and is referenced like 

https://github.com/yuin/goldmark/blob/60df4aadee09cba8a9e28af96d5e9e8883050ff4/renderer/html/html.go#L648
