### ISSUE TITLE
question: Passing state to a rendering extension

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#37]
I'm in the process of creating some link/image extensions that would allow for link resolution/image resize etc. 

For that to work, I need to pass on some document state to the custom link renderer. But I don't see how.

The `Parse` method can take a context, but I don't see a similar way to pass a struct via `Render`. I could create a new `goldmark.Markdown` for each document, but that sounds wasteful.

**Comment by yuin** [comment]
Could you describe details about this requirements?

In current design, such data is intended to be stored in `Node.Attributes` or struct properties of your own ASTNode.

**Comment by bep** [comment]
>Could you describe details about this requirements?

There are several use cases here. I can take one:

* Hugo has a concept of bundles, which stores content files (including Markdown), images, JSON files etc.
* For images, I would maybe want to process them, i.e. resize them to 500x wide or something. It will then get a new URL which will be the new `src` element on the `img` tag.
* To be able to do this, I need the current page, a `page.Page` interface.

Another example that would require the same `page.Page` would be to resolve relative links (e.g. `/blog/post.md` => `/blog/2019/10/05/post/`). This we have an ugly shortcode for today.

Both of these are, in my head, `NodeRendererFunc` implementations.

I will look into `node.Attributes`, which sounds about right.

**Comment by yuin** [comment]
It sounds like attributes are suitable.  Once you had an AST tree, you can traverse it with `ast.Walk` and update node properties and attributes.

**Comment by bep** [comment]
Yes, this works:

```go
 docCtx := pc.Get(documentContextKey)

ast.Walk(n, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
	s := ast.WalkStatus(ast.WalkContinue)
	if docCtx != nil && entering && n.Kind() == ast.KindLink {
		n.SetAttribute(documentContextAttrName, docCtx)
	}
})
```

Thanks for the fast response!
