### ISSUE TITLE
Could `PrecendingCharacter` be replaced by `PrecedingCharacter`

### ISSUE THREAD

**Issue by jsoref** [yuin/goldmark#377]
https://cs.github.com/yuin/goldmark/blob/9d6f314b99ca23037c93d76f248be7b37de6220a/text/reader.go#L33

**Comment by yuin** [comment]
This breaks compatibilities

**Comment by jsoref** [comment]
It's possible to add the correct spelling without dropping the incorrect one…

**Comment by jsoref** [comment]
It's possible to add the correct spelling without dropping the incorrect one…
