### ISSUE TITLE
Unwanted paragraph closing tag in html template tag

### ISSUE THREAD

**Issue by karamme** [yuin/goldmark#38]
First of all, thanks a lot for the work on goldmark. I just tried it with the new release and it works great. Though, there is one minor imperfection:

The `unsafe` option is turned on and there is html code inside a paragraph, like this:

``` 
This is **Bold** <span>Component</span><template>
<div>Name</div>
</template>  **Bold** as well.
```

This will render as:

``` html
<p>This is <strong>Bold</strong> <span>Component</span><template></p>
<div>Name</div>
</template>  **Bold** as well.
```

Notice how the closing tag `</p>` is set too early. If I remove the line break after `<template>` it works as aspected:

``` 
This is **Bold** <span>Component</span><template> <div>Name</div>
</template>  **Bold** as well.
```
``` html
<p>This is <strong>Bold</strong> <span>Component</span><template> <div>Name</div>
</template>  <strong>Bold</strong> as well.</p>
```

Of course I can just move the div up, but there are other divs in my template as well (they also call `</p>` too early) and therefore this one line will become quite long and hard to maintain. Basically, the template tag and everything inside should not call for the automatic setting of `</p>`.

Even though I use Hugo to render, I think this is a goldmark related issue.

**Comment by zzwx** [comment]
Not sure if this is related, but in order to be recognized auto-links seem to require at least one empty line after raw html headers: 

```html
<h2 class="lead">Title</h2>

https://github.com/yuin/goldmark
```

But I also see similar behavior in Visual Studio Code markdown preview so it might be intentional.

Also I have to append extra new line(s) after html like `<div class="row">` for the markdown headers to be recognized:

```html
<div class="row">

## Overview
</div>
```

Otherwise the title looks like raw `## Overview` text.

**Comment by yuin** [comment]
This is not a bug, and works as expected. goldmark gets full compliance with CommonMark spec. You can try this [here](https://spec.commonmark.org/dingus/) and will get same results.

Please refer to [4.6 HTML blocks](https://spec.commonmark.org/0.29/#html-blocks) and [6.8 Raw HTML](https://spec.commonmark.org/0.29/#raw-html) for details.

**Comment by zzwx** [comment]
Thanks for clarifying @yuin!
