### ISSUE TITLE
Table definition does not support signle dash

### ISSUE THREAD

**Issue by zyxkad** [yuin/goldmark#383]
goldmark has [https://github.com/yuin/goldmark/discussions](Discussions) in github.
You should post only issues here. Feature requests and questions should be posted at discussions.

- [ ] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).
    - [x] **Extensions(Autolink without `<` `>`, Table, etc) are not part of CommonMark spec.** You should confirm your output is different from other official renderers correspond with an extension.
- [ ] **goldmark is not dedicated for Hugo**. If you are Hugo user and your issue was raised by your experience in Hugo, **you should consider create issue at Hugo repository at first** .

Please answer the following before submitting your issue:

1. What version of goldmark are you using? : v1.5.4
2. What version of Go are you using? : v1.20
3. What operating system and processor architecture are you using? : N/A
4. What did you do? : <https://go.dev/play/p/F6NSsFoGHe0>
5. What did you expect to see? : <https://gist.github.com/zyxkad/dfee41cf4a1cbdd75c04e8df3253c11b>
6. What did you see instead? :
  ```html
  <p>| F1 | F2 | F3 |
  | - | - | - |
  | 1 | 2 | 3 |</p>
  ```
7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?: Yes, the github renderer

**Comment by jmooring** [comment]
This is behaving as expected with the [CommonMark online demo](https://spec.commonmark.org/dingus/):
<https://spec.commonmark.org/dingus/?text=%7C%20F1%20%7C%20F2%20%7C%20F3%20%7C%0A%7C%20-%20%7C%20-%20%7C%20-%20%7C%0A%7C%201%20%7C%202%20%7C%203%20%7C>

**Comment by zyxkad** [comment]
I'm sorry but I can't open spec.commonmark.
Or if it's expected, is there any plugin can support this type of table?

**Comment by zyxkad** [comment]
Ok sorry for wasting your time, I just saw it in the readme (my first time to use this library, sorry again)

**Comment by jmooring** [comment]
Correction: the Commonmark online demo is irrelevant. The table capability is provided by the built-in table extension, which should adhere to the [GitHub Flavored Markdown Spec](https://github.github.com/gfm/).

In the spec, the [delimiter row ](https://github.github.com/gfm/#delimiter-row)is described:

> consists of cells whose only content are hyphens (-), and optionally, a leading or trailing colon (:), or both, to indicate left, right, or center alignment respectively.

The spec does not specify a minimum number of hyphens, so 1 hyphen shoud work, as it does on GitHub.

Please re-open.
