### ISSUE TITLE
`extension.GFM` doesn't support raw html

### ISSUE THREAD

**Issue by zyxkad** [yuin/goldmark#384]
goldmark has [https://github.com/yuin/goldmark/discussions](Discussions) in github.
You should post only issues here. Feature requests and questions should be posted at discussions.

- [ ] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).
    - [x] **Extensions(Autolink without `<` `>`, Table, etc) are not part of CommonMark spec.** You should confirm your output is different from other official renderers correspond with an extension.
- [ ] **goldmark is not dedicated for Hugo**. If you are Hugo user and your issue was raised by your experience in Hugo, **you should consider create issue at Hugo repository at first** .

Please answer the following before submitting your issue:

1. What version of goldmark are you using? : v1.5.4
2. What version of Go are you using? : v1.20
3. What operating system and processor architecture are you using? : N/A
4. What did you do? : <https://go.dev/play/p/KQZ5WcERa2L>
  ```markdown
  <details>

  # Hidden header

  </details>
  ```
5. What did you expect to see? : 
  ```html
  <details>
  <h1> Hidden header </h1>
  </details>
  ```
6. What did you see instead? : 
  ```html
  <!-- raw HTML omitted -->
  <h1> Hidden header </h1>
  <!-- raw HTML omitted -->
  ```
7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?: Github markdown renderer <https://gist.github.com/zyxkad/f970ffd5a180bc3ba0b62363962c934e>

**Comment by jmooring** [comment]
See `html.WithUnsafe` under <https://github.com/yuin/goldmark#html-renderer-options>
