### ISSUE TITLE
Parser prints strong as emphasis

### ISSUE THREAD

**Issue by khanakia** [yuin/goldmark#392]
goldmark has [https://github.com/yuin/goldmark/discussions](Discussions) in github.
You should post only issues here. Feature requests and questions should be posted at discussions.

- [X] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).
    - [X] **Extensions(Autolink without `<` `>`, Table, etc) are not part of CommonMark spec.** You should confirm your output is different from other official renderers correspond with an extension.
- [X] **goldmark is not dedicated for Hugo**. If you are Hugo user and your issue was raised by your experience in Hugo, **you should consider create issue at Hugo repository at first** .

Please answer the following before submitting your issue:

1. What version of goldmark are you using? : 1.5.4
2. What version of Go are you using? : 1.20.1
3. What operating system and processor architecture are you using? : Mac
4. What did you do? : ran the below code
5. What did you expect to see? : it should print strong
6. What did you see instead? : it printed emphasis
7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?: yes

```go
var source = `
**This is text**
`
func main() {
	doc := goldmark.DefaultParser().Parse(text.NewReader([]byte(source)))
	ast.Walk(doc, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		s := ast.WalkStatus(ast.WalkContinue)
		var err error
		fmt.Println(n.Kind())
		return s, err
	})
}
```

### Outputs
```
Document
Paragraph
Emphasis
Text
Text
Emphasis
Paragraph
Document
```

It should print like this according to https://spec.commonmark.org/dingus/
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">

<document xmlns="http://commonmark.org/xml/1.0">
  <paragraph>
    <strong>
      <text>This is text</text>
    </strong>
  </paragraph>
</document>
```

It print `emphasis` instead of `strong`

**Comment by yuin** [comment]
Spec is definied only for HTML outputs

**Comment by khanakia** [comment]
What do you mean by "Spec is definied only for HTML outputs" ?
