### ISSUE TITLE
Support footnote return links

### ISSUE THREAD

**Issue by Brixy** [yuin/goldmark#40]
```
goldmark v1.1.7
with Hugo 0.60.0
```

As mentioned in gohugoio/hugo/issues/6551 Goldmark seems to not support footnote return links although they are supported by [PHP Markdown extra](https://michelf.ca/projects/php-markdown/extra/#footnotes).

It would be great if Goldmark supported them.

Thank you very much in advance.

**Markdown:**

```
That's some text with a footnote.[^1]

[^1]: And that's the footnote.
```

**Output:**

```
…
<section class="footnotes" role="doc-endnotes"><hr><ol><li id="fn:1" role="doc-endnote"><p>And that's the footnote.</p></li></ol></section>
```

**Comment by DirtyF** [comment]
@yuin Amazing, thank you so much for the prompt fix. 🙏
