### ISSUE TITLE
Linkify bug

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#41]
```go
package main

import (
	"bytes"
	"fmt"
	"log"
	"runtime/debug"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

func main() {

	convert(`
Go to [http://www.example.com](www.example.com) or http://www.example.com.
`)
}

func convert(src string) {
	markdown := goldmark.New(
		goldmark.WithExtensions(extension.Linkify),
	)

	var buf bytes.Buffer
	err := markdown.Convert([]byte(src), &buf)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(buf.String())
}

```

Prints:

```html
<p>Go to <a href="www.example.com"><a href="http://www.example.com">http://www.example.com</a></a> or <a href="http://www.example.com">http://www.example.com</a>.</p>
```

**Comment by yuin** [comment]
@bep This definitely feels strange, but current CommonMark spec renders as this.

Try `Go to [<http://www.example.com>](www.example.com)` [here](https://spec.commonmark.org/dingus/) (URL quoted `<>` is an autolink defined in CommonMark). You will see same nested `<a>` tag. 
But `Go to  [[http://www.example.com](www.example.com)](www.example.com)` is not rendered as nested `<a>` tag.  This is defined in [6.5Links](https://spec.commonmark.org/0.29/#links) 
> Links may not contain other links, at any level of nesting. If multiple otherwise valid link definitions appear nested inside each other, the inner-most definition is used.

This means auto links in CommonMark is regarded as different from link elements. So I recommend you to disable `Linkify` and use `<http://www.example.com>` style auto links.

**Comment by bep** [comment]
>So I recommend you to disable Linkify and use <http://www.example.com> style auto links.

People can disable Linkify if they want, but people are used to GitHub type auto links (which is also how Hugo behaves with Blackfriday). I admit that the test case (which is reported from a Hugo user, but I think since autolinks is a GitHub extension, I would expect it to behave according to their implementation:

Go to [http://www.example.com](http://www.example.com) or http://www.example.com.
Go to [www.example.com](http://www.example.com) or http://www.example.com.

BTW: Your quick response and fixes on the issues raised lately are much appreciated. Nothing finds corner case bugs faster than having some tens of thousands users hit it with a hammer...

**Comment by yuin** [comment]
@bep OK, I've changed the linkify extension behaviour. But this commit also changes CommonMark style autolink(`<>`) behaviour because Linkify uses same AST Node as CommonMark style autolinks.

**Comment by yuin** [comment]
Note: It needs for getting strictly compliance with CommonMark that separating AST nodes between Github flavored style autolinks and CommonMark style autolinks(CommonMark style autolinks in link labels should be rendered as nested `<a>`).
