### ISSUE TITLE
disbale CodeBlockParser but cont get empty result

### ISSUE THREAD

**Issue by zhangziang** [yuin/goldmark#433]
goldmark has [https://github.com/yuin/goldmark/discussions](Discussions) in github.
You should post only issues here. Feature requests and questions should be posted at discussions.

- [ ] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).
    - [ ] **Extensions(Autolink without `<` `>`, Table, etc) are not part of CommonMark spec.** You should confirm your output is different from other official renderers correspond with an extension.
- [ ] **goldmark is not dedicated for Hugo**. If you are Hugo user and your issue was raised by your experience in Hugo, **you should consider create issue at Hugo repository at first** .

Please answer the following before submitting your issue:

1. What version of goldmark are you using? : 
v 1.6.0
3. What version of Go are you using? : 
v 1.21.4
5. What operating system and processor architecture are you using? :
macOS 10.14
7. What did you do? :
parse text with some \t beginning and dont use `CodeBlockParser`
```
test message

    one line with \t beginning
    two line with \t beginning

eof

```
8. What did you expect to see? :
prase result contain text  node, content is `    one line with \t beginning` or `    two line with \t beginning`
10. What did you see instead? :
prase result miss `    one line with \t beginning` and `    two line with \t beginning`
12. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?:
maybe

**Comment by yuin** [comment]
This issue is hard to make a decision that consists with CommonMark spec.

As defined in CommonMark spec, Block elements except indented code block elements can not accept indented lines.
One of the options for this issue is add your own parser which returns `true` for `CanAcceptIndentedLine() bool`.
Other options for this issue is add a functional option that makes Paragraphs indentable.
