### ISSUE TITLE
Incorrect parsing of a nested list inside an empty list item

### ISSUE THREAD

**Issue by Andrew-Morozko** [yuin/goldmark#466]
Failing example
```md
- 
  - foo
```

commonmark:
```html
<ul>
<li>
<ul>
<li>foo</li>
</ul>
</li>
</ul>
```

goldmark:
```html
<ul>
<li></li>
<li>foo</li>
</ul>
```

[commonmark](https://spec.commonmark.org/dingus/?text=-%20%0A%20%20-%20foo) vs [goldmark](https://yuin.github.io/goldmark/playground/?m=-%20%0A%20%20-%20foo&o=0&v=v1.7.4)

[This check](https://github.com/yuin/goldmark/blob/15ade8aace9a9f269846fb83d36fc7bcec875cd5/parser/list_item.go#L43) seems to be the culprit

**Comment by yuin** [comment]
Sorry for my late reply, I've been crazy busy with work. I've fixed issues reported.
