### ISSUE TITLE
BaseBlock.Text changed in v1.7.5

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#470]
Hugo has some tests failing when upgrading to `v1.7.6` that suggest that there are now a trailing newline when calling `.Text` on e.g. `*ast.Heading` that was not there before. 

I assume this is e44645afbb6814bb93536587a5d4af43ad3ab2ef

Old implementation:

```go
// Text implements Node.Text  .
func (n *BaseNode) Text(source []byte) []byte {
	var buf bytes.Buffer
	for c := n.firstChild; c != nil; c = c.NextSibling() {
		buf.Write(c.Text(source))
	}
	return buf.Bytes()
}
```

New implementation:

```go
// Text implements Node.Text.
func (b *BaseBlock) Text(source []byte) []byte {
	var buf bytes.Buffer
	for _, line := range b.Lines().Sliced(0, b.Lines().Len()) {
		buf.Write(line.Value(source))
	}
	return buf.Bytes()
}

```

**Comment by bep** [comment]
>There are no 'correct' definition of the 'text value' of a node especially BlockNodes.

This issue is about _stability_  and not about _correctness_.

**Comment by yuin** [comment]
stability and correctness are connected in practice.
If there is a function that has bugs(including 'incorrect' result) and fixing it leads different results is unstable? Fixing bugs break any code depends on this bug.
