### ISSUE TITLE
`Node.Text` returns HTML elements as plain text (regression from 1.7.4)

### ISSUE THREAD

**Issue by rhysd** [yuin/goldmark#471]
goldmark has [https://github.com/yuin/goldmark/discussions](Discussions) in github.
You should post only issues here. Feature requests and questions should be posted at discussions.

- [x] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).
    - [x] **Extensions(Autolink without `<` `>`, Table, etc) are not part of CommonMark spec.** You should confirm your output is different from other official renderers correspond with an extension.
- [x] **goldmark is not dedicated for Hugo**. If you are Hugo user and your issue was raised by your experience in Hugo, **you should consider create issue at Hugo repository at first** .

Please answer the following before submitting your issue:

1. What version of goldmark are you using? : 1.7.8
2. What version of Go are you using? : 1.23.1
3. What operating system and processor architecture are you using? : macOS 13
4. What did you do? : Ran the following code.
5. What did you expect to see? : Expected to print `"foo"`
6. What did you see instead? : Printed `"<code>foo</code>"`, which means that the `<code>` and `</code>` are plain texts. But actually they should be part of HTML elements.
7. Did you confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/) or other official renderer correspond with an extension?: `Node.Text` is not a functionality the online demo provides.

```go
package main

import (
	"fmt"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/text"
)

func main() {
	md := goldmark.New()

	input := []byte("<code>foo</code>")
	root := md.Parser().Parse(text.NewReader(input))

	fmt.Printf("%q\n", root.Text(input))
}
```

This is a regression from v1.7.4. With goldmark v1.7.4, the above code prints `"foo"` as expected.

**Comment by yuin** [comment]
See https://github.com/yuin/goldmark/releases/tag/v1.7.8

**Comment by rhysd** [comment]
So the meaning of the `Node.Text` has changed, am I correct?

- v1.7.4: It returned the stripped plain text
- v1.7.8: It now returns the original markdown text (as much as possible)

**Comment by yuin** [comment]
Yes. As I've wrote there's no 1 'correct' text representation of most nodes.
All Node.Text methods are deprecated now. If you applies some linter, it will claim that Node.Text is deprecated.
I recommend you to update your code to avoid Node.Text.
All Node.Text can be replaced with other public functions.

**Comment by rhysd** [comment]
Thank you for the clarification. Yes, I understood that the method had been deprecated and I will stop using it as soon as possible. I just wanted a clarification :)
