### ISSUE TITLE
Apostrophe breaks Linkify

### ISSUE THREAD

**Issue by cup** [yuin/goldmark#49]
Using this file:

~~~go
package main
import (
   "bytes"
   gm "github.com/yuin/goldmark"
   "github.com/yuin/goldmark/extension"
)
func main() {
   var s1 = []byte("https://github.com/sunday's")
   var s2 bytes.Buffer
   gm.New(gm.WithExtensions(extension.Linkify)).Convert(s1, &s2)
   print(s2.String())
}
~~~

I get this result:

~~~html
<p><a href="https://github.com/sunday">https://github.com/sunday</a>'s</p>
~~~

With github.com parser, I get this result:

~~~html
<p><a href="https://github.com/sunday's">https://github.com/sunday's</a></p>
~~~

Example:

https://github.com/sunday's

**Comment by yuin** [comment]
@cup Currently, Linkify extension just uses regexs below:

```
var wwwURLRegxp = regexp.MustCompile(`^www\.[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b(?:[-a-zA-Z0-9@:%_\+.~#?&//=\(\);,]*)`)

var urlRegexp = regexp.MustCompile(`^(?:http|https|ftp):\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=\(\);,]*)`)
```

You've reported this kind of issue before. It would be great if you report these issues together this kind of issues instead of reporting case by case .

**Comment by cup** [comment]
@yuin yes I am sorry. I did not intend to do this, but I discovered both issue separately. Thank you for the reply.

**Comment by yuin** [comment]
@cup No worries. Linkify implementation is a little lazy so may have different result from Github's renderer. If you notice these results, please feel free to report issue case by case.
