### ISSUE TITLE
Consider adding a context (data holder) to Render

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#53]
This is a follow up to #37

So, setting state on the nodes in the AST and then use that while rendering works, but ...

* It makes for some fairly clumsy and verbose code
* It breaks the separation of concerns (adding rendering code to the parser)

What I'm now doing instead is something ala:

```go
        w := renderContext{
		BufWriter: bufio.NewWriter(buf),
		renderContextData: renderContextDataHolder{
			rctx: ctx,
			dctx: c.ctx,
		},
	}

	if err := c.md.Renderer().Render(w, ctx.Src, doc); err != nil {
		return nil, err
	}
```

This works great , and I don't mind doing it like this (this is entirely internal), but the down side is that it may stop working in the future if you decide to wrap the writer or something.

**Comment by yuin** [comment]
I think it might be better that you do not use context data if you can.

You commented as 

```go
docCtx := pc.Get(documentContextKey)

ast.Walk(n, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
	s := ast.WalkStatus(ast.WalkContinue)
	if docCtx != nil && entering && n.Kind() == ast.KindLink {
		n.SetAttribute(documentContextAttrName, docCtx)
	}
})
```

But I would like to recommend 

```go
docCtx := pc.Get(documentContextKey)

ast.Walk(n, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
	s := ast.WalkStatus(ast.WalkContinue)
	if docCtx != nil && entering && n.Kind() == ast.KindLink {
		// update link href, resolve relative path, add class etc
	}
})
```

Let's think about a case we have a LateX renderer in the future. If above logics are implemented in Renderer using context, we have to implement same logics in both HTML renderer and LateX renderer.

If we update AST itself and renderer simply renders AST without logics, we can change renderers more easily.

**Comment by bep** [comment]
> we have to implement same logics in both HTML renderer and LateX renderer.

Yes, that is a concern, and this issue can just sit here for a while. The thing is, in my perspective:

* The "plugin interface" I currently have to offer the Hugo users are Go templates, and from a practical perspective it makes sense to just hand them a context and ask them to render the link (or not). And given that approach, it does not make much sense to change the AST.
* And even when multiple renderers are added, I don't think we would get very far by doing AST manipulation alone. For a fictionary AMP renderer, the AMP and HTML links would need to point to different locations. Hugo supports this, but it cannot be done in the AST without additional mapping.

I think I need to think a little about how to add something for HTML that would make any future LateX etc. too hard to do. 

/cc @regisphilibert

**Comment by yuin** [comment]
>  For a fictionary AMP renderer, the AMP and HTML links would need to point to different locations.

Why this means that we need context for renderers?  We can resolve contextual things in AST transformation phase, then do output format specific things in rendering phase.

I think Hugo's requirements is uncommon. I would like to avoid breaking APIs in response to it without being careful.
I keep this issue as opened and want to listen to others' opinions.

You can use the wrapping writer approach until this issue is resolved. You can reduce what goldmark changes impacted Hugo by wrapping code where you extract your context from `w` . 

```go
rctx, dctx := GetContext(w)
```

**Comment by bep** [comment]
>Why this means that we need context for renderers? W

I see similar discussions in the CommonMark discussion forum when talking about css classes as attributes, which is entirely a rendering instruction thing, but it is practical to pass in as attributes.

But at least, in that case, the renderer who doesn't care about CSS classes can ignore them.

If I have a document that I want to render to both AMP and HTML, and the `Destination` set on the AST node is `/README.md` the rendered references would be something like `/README.html` and `/README.amp.html` (or something).

Multiple values and very much connected to the renderers.

So, while multiple output formats from the same AST may be uncommon, having a way to do "link translation" would be very common. And even a simple `/README.md` to `/README.html` as an AST transformation seems very much like breaking the separation of concerns.

**Comment by yuin** [comment]
>> So, while multiple output formats from the same AST may be uncommon

I do not think so. Many markdown library has LateX renderer(As you known [blackfriday](https://github.com/russross/blackfriday/blob/master/latex.go) has it).

**Comment by robmuh** [comment]
Personally I'm much more inclined to follow the direction yuin is laying out (particularly that has zero dependency on contexts at all). Having spent way more time with Pandoc internals than I would like I think there is a lot to be learned from there. To date, Goldmark seems to be including all the best internal architecture from Pandoc (and omitting the bad). It might be instructive for folks to look at Pandoc internals --- and particularly the Lua plugin architecture they have --- just as a comparison of different approaches to these issues. The Pandoc AST is rock solid and my limited work with Goldmark AST so far seems very similar. I strongly recommend at least fully understanding the Pandoc AST before writing it off. They already have JSON renders of it and such and although 100% compatibility with the Pandoc AST might be a stretch, eventually having an import/export of such might be worth consideration.

**Comment by bep** [comment]
> my limited work with Goldmark AST so far seems very similar.

You understand that this isn't about the AST, right?

**Comment by robmuh** [comment]
> You understand that this isn't about the AST, right?

It's actually an important part of this thread because one suggested approach fundamentally depends on it:

> If we update AST itself and renderer simply renders AST without logics, we can change renderers more easily. (yuin)

**Comment by bep** [comment]
>If we update AST itself and renderer simply renders AST without logics

It's @yuin ' s project and up to him, but the above statement is flawed. The HTML renderer has plenty of HTML related logic as is.  Adding state to the AST that is only relevant for one format isn't ... great. I guess it can be practical/pragmatic in some cases (ref. the CSS classes as attributes discussion), but not as a general rule.

**Comment by robmuh** [comment]
Thanks for the clarification. Sounds like you are pushing for keeping everything as non-specific to any particular output format, which I strongly support. My mention of Pandoc AST is because by focusing on the core (and leaving all specific formats out of it) they have achieved almost universal modularity free from any tight format couplings or internal renderer dependencies.  I'll dig into the code base more. Thanks again.

**Comment by bep** [comment]
I still think this is a good idea, and obviously better to add sooner rather than later (re API breakage).

**Comment by yuin** [comment]
I read the Hugo's doc roughly. And, at least, this is not necessary for renderer hooks.

'context' means contextual for the documents(AST). Renderer hooks seems to be related with sites rather than documents. This means renderer hooks should be configurations for a renderer in goldmark's architecture design. If I implement a functionality like the renderer hook, I will do like the following:

```go

// Implement my link renderer(NodeRenderer)
type MyLinkRenderer {
//omit
}

func main() {
    md := goldmark.New(
        //omit
    }
    // read renderer-link.html
    md.Renderer().AddOptions(
			renderer.WithNodeRenderers(
				util.Prioritized(NewMyLinkRenderer(rendererLinkConfig), 0),
			),
}

```
