### ISSUE TITLE
How to apply microtypographic rules to Markdown?

### ISSUE THREAD

**Issue by DirtyF** [yuin/goldmark#59]
1. What version of goldmark are you using? : [v1.11.1](https://github.com/gohugoio/hugo/blob/40a092b0687d44ecb53ef1fd53001a6299345780/go.mod#L57) (Hugo 0.60.1)
2. What version of Go are you using? : go1.13.4
3. What operating system and processor architecture are you using? darwin/amd64 (macOS 10.15.1)
4. What did you do? : Write Markdown in french language
5. What did you expect to see? : french typographic rules applied (like inserting a non-breakable space before a question mark)
6. What did you see instead? : no french typographic rules 
7. (Feature request only): Why you can not implement it as an extension?: Not a Go programmer

How should be french typographic rules applied, through an extension, or is it something that is dependendant of the Go language itself? Or another Go Package?  SmartyPants but with more rules specific to a language.

For instance, languages like PHP have libs to handle this https://github.com/jolicode/JoliTypo

Some of the french typographic rules are liste by Grammalecte Firefox extension:

![](https://grammalecte.net/grammalecte/img/screenshots/lo-formateur-de-texte.png)

**Comment by yuin** [comment]
This can be implemented as a goldmark extension. But I can not implement this because I don't know about French. (Can you imagine french people implement Japanese relatad functionalies?).

I keep this issue opened and wait to see someone creating this extension.

**Comment by inwardmovement** [comment]
@yuin can my [issue here](https://github.com/russross/blackfriday/issues/439) help you implement non-breaking spaces/french punctuation support?

**Comment by DirtyF** [comment]
A similar attempt as a Hugo module: https://github.com/jygastaud/hugo-microtypo

**Comment by yuin** [comment]
@inwardmovement @dertseha 

Again, I'm not going to implement this. This is an open source project. 
Regional functionalities should be implemented by people who belongs the region.

**Comment by DirtyF** [comment]
🙏 @yuin thanks for pointing us in the right direction, closing this as `wontfix`.

**Comment by kosssi** [comment]
I'm used a node script to implement this with https://github.com/sapegin/richtypo.js but I preferred have an extension by default in hugo like:

```toml
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = true
    [markup.goldmark.typographer]
      language = french
```

I'm not Go developer :'(
Maybe @DirtyF you could reopen this issue and a french dev see it :D

**Comment by DirtyF** [comment]
@kosssi I won't because I value Maintainers over Users in open source projects. If a french Go developer has the appetite to fix it, he will.

**Comment by cilex-ft** [comment]
> I'm used a node script to implement this with https://github.com/sapegin/richtypo.js 

@kosssi Please: how do you use this script? Can you show an example?

Thank you!

@yuin of course I'd love to write this extension ...if only I were a real programmer. Which extension could I use as an example? Is there a guide somewhere about howto write, compile, test... an extension? Thank you

**Comment by yuin** [comment]
https://github.com/yuin/goldmark/blob/master/extension/typographer.go

Typographer extension can be used as an example. There are no guides yet, but many people created extensions referring builtin extensions.
