### ISSUE TITLE
Remove the 1.12.x tests or fix the library to conform to unsigned shifts change since 1.13

### ISSUE THREAD

**Issue by zzwx** [yuin/goldmark#60]
According to https://github.com/yuin/goldmark/blob/master/.github/workflows/test.yaml, 
GitHub Actions are using `1.12.x` tests that make sense if the library is compatible with 1.12 which is not by definition in `go.mod`.

On the other hand the only problem for not being compatible with `1.12` is unsigned shift operations. Is it then worth converting those loops causing trouble to using `uint` instead?

**Comment by yuin** [comment]
This issue has already been resolved in ec246695c5f8d05692da189f89645495c277eba8.

**Comment by zzwx** [comment]
Sorry didn't notice! You are fast!
