### ISSUE TITLE
goldmark can't emphasized the specific Chinese character

### ISSUE THREAD

**Issue by chenzhiwei** [yuin/goldmark#61]
After using goldmard process the markdown text `**「刻舟求剑」**`, the result is still `**「刻舟求剑」**`, but the expected is **「刻舟求剑」**.

1. What version of goldmark are you using? : v1.1.11
2. What version of Go are you using? : 1.12
3. What operating system and processor architecture are you using? : Hugo v0.60.1 on macOS
4. What did you do? : Create a markdown file with `**`
5. What did you expect to see? : The words should be emphasized 
6. What did you see instead? : The words was not emphasized
7. (Feature request only): Why you can not implement it as an extension?: not applicable

**Comment by yuin** [comment]
This is known CommonMark spec.(see [here](https://talk.commonmark.org/t/single-asterisks-in-subsequent-words-should-not-lead-to-emphasis/1035/6) etc).

CommonMark spec are created by westerners, So they did not take account into our languages(I'm Japanese). 

I plan to make goldmark better in CJK even though it breaks CommonMark compliance.

**Comment by chenzhiwei** [comment]
The GitHub issue editor can handle CJK properly, so maybe it is not CommonMark complaint?

Need to make goldmark as a super set of CommonMark to better support CJK.

**Comment by yuin** [comment]
CommnonMark emphasis rule is complicated as [hell](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis), it probably contains ambiguity case.

At least, text like '今日は**「晴れ」**です' is not emphasized on Github issue editor.

**Comment by chenzhiwei** [comment]
@yuin OK, you win.
