### ISSUE TITLE
Linkify does not work after Chinese characters

### ISSUE THREAD

**Issue by chenzhiwei** [yuin/goldmark#62]
goldmark does not linkify following links:

```
搜索引擎链接https://www.google.com
```

OR

```
搜索引擎链接：https://www.google.com
```

1. What version of goldmark are you using? : v1.1.11
2. What version of Go are you using? : 1.12
3. What operating system and processor architecture are you using? : Hugo v0.60.1 on macOS
4. What did you do? : Put a link after Chinese characters
5. What did you expect to see? : The link should be automatically created
6. What did you see instead? : The link was not automatically created
7. (Feature request only): Why you can not implement it as an extension?: not applicable

**Comment by yuin** [comment]
[GFM spec](https://github.github.com/gfm/#autolinks-extension-) says

> Autolinks can also be constructed without requiring the use of < and to > to delimit them, although they will be recognized under a smaller set of circumstances. All such recognized autolinks can only come at the beginning of a line, after whitespace, or any of the delimiting characters *, _, ~, and (.

So "beginning of a line, after whitespace, or any of the delimiting characters *, _, ~, and (." is currently required to make it linked.

**Comment by chenzhiwei** [comment]
I think it is better to add a `gfm` parameter to control the goldmark support the GFM format.

**Comment by yuin** [comment]
As mentioned in [README](https://github.com/yuin/goldmark#built-in-extensions), Linkify implements GFM .
