### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by prologic** [yuin/goldmark#7]
Please add Release Notes to your releases!

You *may* borrow my script/tools that I use for this [tools/release.sh](https://github.com/prologic/bitcask/blob/master/tools/release.sh)

This will help a lot for folks watching releases and not all commits :)

**Comment by yuin** [comment]
I will always add a release note if there are minor level(x.X.x) changes.

Patch level changes(x.x.X) is almost just a bug fix and a release for Go module(`go mod`) users who want to use latest version of the package.

**Comment by prologic** [comment]
Okay thanks! I'll un-watch then :D
