### ISSUE TITLE
Linkify inside code ticks

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#74]
```go
package main

import (
	"bytes"
	"fmt"
	"log"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

func main() {

	markdown := goldmark.New(
		goldmark.WithExtensions(extension.Linkify),
	)
	var buf bytes.Buffer
	err := markdown.Convert([]byte(`This is a `+"`"+`git@github.com:vim/vim`+"`"), &buf)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(buf.String())
}
```

Prints

```
<p>This is a <a href="mailto:%60git@github.com">`git@github.com</a>:vim/vim`</p>
```

```

Note that this isn't about #70 -- but the fact that the URL inside code ticks gets linkified. The "try it" at  https://commonmark.org/help/tutorial/02-emphasis.html does not do that.

**Comment by yuin** [comment]
http://www.pokemon.com/Pikachu_]

**Comment by yuin** [comment]
@bep 

Note: Autolink without '<' '>' is not a commonmark spec. You should try this kind of tests as GFM, not CommonMark.

I think this is an undefined and ambiguous behavior about GFM. GFM spec is relatively ambiguous compared with CommonMark spec.

`` `git@github.com `` is a valid email address. GFM do not say about autolink predecence.

I do not agree with 'defined by program works', so even with GitHub markdown renderer works like it, I think it is an undefined and ambiguous behavior.

GFM says

> All such recognized autolinks can only come at the beginning of a line, after whitespace, or any of the delimiting characters *, _, ~, and (.

Whitespace triggers AutoLinkParser and `` `git@github.com `` is a valid email address, this text was parsed as an autolink. I've disallowed punctuations at first character about emails now. But downside of this is some valid email addresses now are not autolinked.

**Comment by bep** [comment]
Can you tag a new release with the latest commit? I plan a Hugo release tomorrow.

**Comment by yuin** [comment]
@bep I've made a new release now.
