### ISSUE TITLE
HTML in backticks is removed

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#76]
```go
package main

import (
	"bytes"
	"fmt"
	"log"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

func main() {

	markdown := goldmark.New(
		goldmark.WithExtensions(extension.Linkify),
	)
	var buf bytes.Buffer
	err := markdown.Convert([]byte("´"+"<p></p>"+"`"), &buf)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(buf.String())
}

```

Produces

```bash
<p>´<!-- raw HTML omitted --><!-- raw HTML omitted -->`</p>thi i
```

Note that I'm not totally absolute about this issue. I have been driving for Hugo's site use `unsafe=false`, but I glanced the above example, and now I'm thinking. I think you should preserve HTML inside code ticks (aka code examples), even in "safe mode".

**Comment by mdigger** [comment]
```markdown
´<p></p>` - text with HTML tags
`<p></p>` - code
```

**Comment by yuin** [comment]
@mdigger Thanks for your comment.

@bep As @mdigger says your sample is not a code span. `´` does not trigger code spans

**Comment by bep** [comment]
Oh, sorry ...
