### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by mironovalexey** [yuin/goldmark#8]
It seems that there should be one more builtin goldmark extension - [yaml metadata block](https://github.blog/2013-09-27-viewing-yaml-metadata-in-your-documents/). Then real GFM is fully supported.

**Comment by yuin** [comment]
I've considered this before, it is hard to make this a built-in extension.

goldmark has a policy "depends only on standard libraries" . Unfortunately, go has no standard libraries on YAML.
So I intend to implement functions that depend on 3rd party libraries as external projects.

Or, we can implement a parser supports subset of YAML(YAML has a lot of functionalities than JSON, it
is not reasonable that implement full set of YAML for just this). But I give a preference external projects over subset of YAML parser.

How you do you feel about this?

**Comment by mironovalexey** [comment]
Hm. How about this...

Just seperate "non -GFM" extensions into standalone packages. Then anyone can compile only the necessary stuff, and there's no need to care about dependencies. This can be an external repo if you do not external deps in core goldmark.

I would suggest to extract from core `header attrs`, definition list`, `typographer` and  add `meta`.

So everyone can suggest own extension in this repo. Extensions in external repos can be linked from README.

**Comment by yuin** [comment]
Thanks for your suggestion.

Why I've included these libraries in this repository is just other libraries(blackfriday)  do that. 
Your suggestion sounds good, but I've already released this repository as v1.x.x
I prefer to avoid breaking changes. This is a `go.mod` project. If we follow [Go versioning policy](https://github.com/golang/go/wiki/Modules#semantic-import-versioning), big breaking change makes goldmark `v2` .

Thus I want to make my built-in library policy "GFM and MarkdownExtra related functions that can be implemented by go standard libraries are included as built-in extension"(Typographer is an exception...).

`meta` will be a new repository.

By the way, I supposed this function, so I've designed it can be implement as an extension.

```go
func Convert(source []byte, w io.Writer, opts ...parser.ParseOption) error
```

Convert can take optional arguments `opts` .  You can pass a context created by `parser.NewContext()` .

`meta` extension usage will be like the following:

```go
context := parser.NewContext()
md.Convert(source, w, parser.WithContext(context))
mdmeta := meta.Get(context)
```

**Comment by mironovalexey** [comment]
As I stand, meta struct should be available from renderer and  could have default imlemenation ([github-like tables](https://github.com/gohugoio/hugo/blob/master/docs/content/en/about/benefits.md)):  ~ goldmark.WithRendererOptions(meta.AsTable())

**Comment by yuin** [comment]
If you want to render meta struct as a table, you can use `ASTTransformer` .
After AST was created, you can insert the table into head to the tree.

Footnote extension uses `ASTTransformer` in similar way.

**Comment by mironovalexey** [comment]
Ah, meta is not included in AST. I am sorry.

Don't you like this way of accessing data collected during the parsing?
https://python-markdown.github.io/extensions/meta_data/#accessing-the-meta-data
https://github.com/CaliStyle/markdown-it-meta#use

**Comment by yuin** [comment]
I've considered the way like pythonmark-down and markdown-it.
meta extension collects meta in parsing phase and stores it to a `ParseCotext` .

You can get meta that are stored in a `ParseContext` as described above.
If you like to render meta as a table, you can add an `ASTTransformer` .

**Comment by mironovalexey** [comment]
No, I mean 
```
md.Convert()
log.println(md.Meta)
```

Just to simplify.

**Comment by yuin** [comment]
I do not like the way because md is designed as thread-safe.

**Comment by mironovalexey** [comment]
Reasonable. Thank you for the detailed explanation.

**Comment by yuin** [comment]
I created the [goldmark-meta](http://github.com/yuin/goldmark-meta).

If you have any concerns or ideas, please let me know at the goldmark-meta repository.
