### ISSUE TITLE
nodeRendererFuncs check error

### ISSUE THREAD

**Issue by mdigger** [yuin/goldmark#80]
https://github.com/yuin/goldmark/blob/2c9db0c8faca9f8e6c6d708677ab34bd1bb51c61/renderer/renderer.go#L164

It is necessary to verify that the corresponding renderer is registered and that we are not going outside the slice. If you add a new type and place it in the AST tree, but do not define a renderer for it, then an error occurs that goes beyond the limits of the slice.

**Comment by yuin** [comment]
Yes, I knew it. It should fail if a renderer for the node does not exist. Even if we check the existence, it just makes error message some friendly. It is not changed that program fails immediately.
