### ISSUE TITLE
[Proposal] - Rendering Flag for wrapping heading ids with spans

### ISSUE THREAD

**Issue by dudleycodes** [yuin/goldmark#86]
> 8. (Feature request only): Why you can not implement it as an extension?:

If this proposal can be accomplished via an extension and invoked via a flag, then this is a proposal for an extension. I'm not familiar enough with this project's architecture to adequately answer.

**Background**

While working on a website using [GUHO](https://github.com/gohugoio/hugo), which uses this project I came across this issues and made a feature request ([here](https://github.com/gohugoio/hugo/issues/6711)). After checking it out the project maintainer suggested I add it as a feature request on this project.

**The Issue**
Many websites include non-scrolling headers that are fixed to the top and have a defined height. When clicking on a URL anchor (#fragment) browsers do not respect the height of the fixed header resulting in users being taken too far down the page.

The most efficient way (for web browsers) to fix this issue would to be to have the headings wrap the DOM id in a span, like so:

```html
<h3><span id="one"></span>one</h3>
```

Rather than: `<h3 id="one">one</h3>`

Then developers could style appropriately, like so:

```css
h1,h2,h3,h4,h5,h6{ position:relative; }
h1,h2,h3,h4,h5,h6 span{ position:absolute; top:-120px;}
```

**Proposal**
Add a flag to the goldmark renderer that will nest the DOM ids as shown in the above example inside of a span element.

**Comment by yuin** [comment]
@dudleycodes 

This can be implemented as an extension.

Write a rendering function for `ast.Heading`
https://github.com/yuin/goldmark/blob/master/renderer/html/html.go#L227

and override the default rendering function
https://github.com/yuin/goldmark/blob/master/renderer/html/html.go#L166
