### ISSUE TITLE
Support footnote return links content customization

### ISSUE THREAD

**Issue by inwardmovement** [yuin/goldmark#95]
It would be great if we could customize the footnote return links content.

**Comment by adiabatic** [comment]
The [, the ⏎, and the ], right?

**Comment by inwardmovement** [comment]
The element we click on to get back to the original note yeah, ⏎

**Comment by jzeneto** [comment]
Hi, I too want to get this done. For instance, changing from default character, ⏎, to an up arrow, ↑ (which makes more sense), via configuration.
